<x-layouts.app title="Fixed Asset & Depresiasi"><div class="page-container"><x-ui.page-header title="Fixed Asset & Depresiasi" />
<div class="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-3">
<x-ui.stat-card label="Total Aset Tetap" value="{{ number_format($assets->count()) }}" icon="briefcase" tone="brand" :value-class="'text-[24px] leading-tight'" />
<x-ui.stat-card label="Nilai Perolehan" value="Rp {{ number_format((float) $assets->sum('acquisition_cost'), 0, ',', '.') }}" icon="banknote" tone="info" :value-class="'text-[18px] leading-tight'" />
<x-ui.stat-card label="Kategori Aset" value="{{ number_format($categories->count()) }}" icon="grid" tone="violet" :value-class="'text-[24px] leading-tight'" />
</div>
<p class="mt-2 text-slate-500">Register aset, straight-line depreciation, fiscal control, dan balanced posting.</p><button type="button" class="inline-flex inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="category-drawer" aria-haspopup="dialog"><x-ui.icon name="plus" class="h-4 w-4" />Kategori</button>
<button type="button" class="btn-brand inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="asset-register-drawer" aria-haspopup="dialog"><x-ui.icon name="plus" class="h-4 w-4" />Register Aset</button>
@if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-4">{{ session('status') }}</div>@endif @if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
<div class="mt-6 grid gap-5 lg:grid-cols-3">

</div>
<div class="mt-8 space-y-3">@forelse($assets as $asset)<x-ui.card><div class="flex flex-wrap items-center justify-between gap-3"><div><strong>{{ $asset->code }} — {{ $asset->name }}</strong><p class="text-sm text-slate-500">{{ $asset->category?->name }} · Cost {{ number_format((float)$asset->acquisition_cost,2,',','.') }} · {{ $asset->useful_life_months }} bulan @if($asset->status==='disposed')<span class="ml-1 rounded-full bg-red-50 px-2 py-0.5 text-xs font-bold text-red-700">DILEPAS {{ $asset->disposed_at?->format('d/m/Y') }} · Hasil jual Rp {{ number_format((float)$asset->disposal_proceeds,2,',','.') }}</span>@endif</p></div><div class="flex flex-wrap gap-2">@if($asset->status==='active')<form method="post" action="/admin/fixed-assets/{{ $asset->id }}/depreciate" class="flex flex-wrap gap-2">@csrf<select name="fiscal_period_id" required class="rounded-xl border p-2">@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }}</option>@endforeach</select><input type="date" name="depreciation_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-2"><input type="hidden" name="idempotency_key" value="depreciation-{{ $asset->id }}-{{ today()->format('Ym') }}"><button class="rounded-xl bg-slate-800 px-4 text-white">Post depresiasi</button></form><form method="post" action="/admin/fixed-assets/{{ $asset->id }}/dispose" class="flex flex-wrap gap-2">@csrf<input type="date" name="disposal_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-2"><input type="number" step=".01" min="0" name="proceeds" value="0" required placeholder="Hasil jual (Rp)" class="rounded-xl border p-2 w-40"><input type="hidden" name="idempotency_key" value="disposal-{{ $asset->id }}-{{ uniqid() }}"><button class="rounded-xl bg-red-700 px-4 text-white" data-confirm="Lepas aset ini? Jurnal disposal (akumulasi, nilai perolehan, hasil jual, laba/rugi) akan diposting permanen dan tidak dapat dibatalkan.">Lepas Aset</button></form>@endif</div></div></x-ui.card>@empty<div class="rounded-2xl border border-dashed p-8 text-center">Belum ada aset tetap.</div>@endforelse</div>
<div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Tanggal</th><th>Aset</th><th>Nilai</th><th>Posted</th></tr></thead><tbody>@forelse($depreciations as $d)<tr><td>{{ $d->depreciation_date->format('d/m/Y') }}</td><td>{{ $d->asset?->code }}</td><td>{{ number_format((float)$d->amount,2,',','.') }}</td><td>{{ $d->posted_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center">Belum ada depresiasi.</td></tr>@endforelse</tbody></table></div></div>
<button type="button" class="inline-flex inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="dep-mapping-drawer" aria-haspopup="dialog"><x-ui.icon name="plus" class="h-4 w-4" />Mapping Depresiasi</button>
<x-ui.drawer id="category-drawer" title="Kategori Aset">
<form method="post" action="/admin/fixed-assets/categories" class="grid gap-4">@csrf<h2 class="font-bold">Kategori Aset</h2><input name="code" required placeholder="Kode kategori" class="rounded-xl border p-3"><input name="name" required placeholder="Nama kategori" class="rounded-xl border p-3"><input type="number" min="1" name="default_useful_life_months" required placeholder="Umur default (bulan)" class="rounded-xl border p-3"><button class="rounded-xl bg-slate-900 p-3 text-white">Simpan kategori</button></form>
</x-ui.drawer>

<x-ui.drawer id="asset-register-drawer" title="Register Aset Tetap">
<form method="post" action="/admin/fixed-assets" class="grid gap-4">@csrf<h2 class="font-bold">Register Aset</h2><select name="fixed_asset_category_id" required class="rounded-xl border p-3">@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->code }} — {{ $c->name }}</option>@endforeach</select><select name="project_id" class="rounded-xl border p-3"><option value="">Tanpa proyek</option>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->code }}</option>@endforeach</select><input name="code" required placeholder="Kode aset" class="rounded-xl border p-3"><input name="name" required placeholder="Nama aset" class="rounded-xl border p-3"><input type="date" name="acquisition_date" required class="rounded-xl border p-3"><input type="date" name="depreciation_start_date" required class="rounded-xl border p-3"><input type="number" step=".01" name="acquisition_cost" required placeholder="Harga perolehan" class="rounded-xl border p-3"><input type="number" step=".01" min="0" name="residual_value" value="0" required placeholder="Nilai residu" class="rounded-xl border p-3"><input type="number" min="1" name="useful_life_months" required placeholder="Umur manfaat bulan" class="rounded-xl border p-3"><button class="rounded-xl bg-[var(--brand-primary)] p-3 text-white">Register aset</button></form>
</x-ui.drawer>

<x-ui.drawer id="dep-mapping-drawer" title="Mapping Depresiasi">
<form method="post" action="/admin/finance/mappings" class="grid gap-4">@csrf<h2 class="font-bold">Mapping Depresiasi</h2><input type="hidden" name="event_type" value="asset_depreciation"><select name="entry_side" class="rounded-xl border p-3"><option value="expense_debit">Depreciation Expense Debit</option><option value="accumulated_credit">Accumulated Depreciation Credit</option></select><select name="account_id" required class="rounded-xl border p-3">@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->code }} — {{ $a->name }}</option>@endforeach</select><button class="rounded-xl bg-violet-700 p-3 text-white">Simpan mapping</button></form>
</x-ui.drawer>

<x-ui.drawer id="disposal-mapping-drawer" title="Mapping Disposal Aset">
<form method="post" action="/admin/finance/mappings" class="grid gap-4">@csrf<h2 class="font-bold">Mapping Disposal (ADR-056)</h2><p class="text-sm text-slate-500">Simpan kelima sisi berikut sebelum melepas aset: akumulasi (debit), nilai perolehan (kredit), hasil jual (debit), laba disposal (kredit), rugi disposal (debit).</p><input type="hidden" name="event_type" value="asset_disposal"><select name="entry_side" class="rounded-xl border p-3"><option value="accumulated_debit">Accumulated Depreciation Debit</option><option value="asset_cost_credit">Asset Cost Credit</option><option value="proceeds_debit">Proceeds / Kas Debit</option><option value="gain_credit">Gain on Disposal Credit</option><option value="loss_debit">Loss on Disposal Debit</option></select><select name="account_id" required class="rounded-xl border p-3">@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->code }} — {{ $a->name }}</option>@endforeach</select><button class="rounded-xl bg-violet-700 p-3 text-white">Simpan mapping</button></form>
</x-ui.drawer>
<button type="button" class="mt-4 inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="disposal-mapping-drawer" aria-haspopup="dialog"><x-ui.icon name="plus" class="h-4 w-4" />Mapping Disposal</button>
</x-layouts.app>
