<x-layouts.app title="Marketing & Tender"><section class="mx-auto max-w-7xl px-6 py-10"><h1 class="text-3xl font-black">Marketing & Tender</h1><div class="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-5">@foreach($metrics as $label=>$value)<div class="rounded-xl border bg-white p-4"><p class="text-xs uppercase text-slate-500">{{ str_replace('_',' ',$label) }}</p><strong class="text-2xl">{{ $value }}{{ str_contains($label,'rate')?'%':'' }}</strong></div>@endforeach</div>@if(session('status'))<div class="mt-5 rounded-xl bg-emerald-50 p-4">{{ session('status') }}</div>@endif @if($errors->any())<div class="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
<div class="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
@php($intelCards = [['Win Rate', $intel['win_rate'] === null ? '-' : number_format($intel['win_rate'],1,',','.').'%', 'Won / (Won+Lost)'], ['Tender Won', $intel['won'], 'Nilai Rp '.number_format((float) $intel['won_value'],0,',','.')], ['Lost Opportunity', 'Rp '.number_format((float) $intel['lost_opportunity'],0,',','.'), 'Total nilai tender kalah'], ['Rata-rata vs HPS', $intel['avg_vs_hps_pct'] === null ? '-' : number_format($intel['avg_vs_hps_pct'],2,',','.').'%', ($intel['top_competitor'] ? 'Juara terbanyak: '.$intel['top_competitor'] : 'Belum ada data peserta')]])
@foreach($intelCards as [$label,$value,$hint])<x-ui.stat-card :label="$label" :value="$value" :hint="$hint" />@endforeach
</div>
<div class="mt-6 grid gap-5 lg:grid-cols-3">
<form method="post" action="/admin/tenders/competitors" class="grid gap-2 rounded-2xl border bg-white p-5 no-print">@csrf<h2 class="font-bold">Kompetitor Baru</h2><input name="code" required placeholder="Kode" class="rounded-xl border p-3"><input name="name" required placeholder="Nama perusahaan pesaing" class="rounded-xl border p-3"><button class="rounded-xl bg-slate-900 p-3 text-white">Daftarkan</button></form>
<form method="post" action="/admin/tenders/participants" class="col-span-1 lg:col-span-2 grid gap-2 rounded-2xl border bg-white p-5 no-print">@csrf<h2 class="font-bold">Peserta & Hasil Tender</h2><select name="tender_id" required class="rounded-xl border p-3"><option value="">Pilih tender</option>@foreach($recentTenders as $rt)<option value="{{ $rt->id }}">{{ $rt->number }} — {{ $rt->project_name }}</option>@endforeach</select><div class="grid gap-2 sm:grid-cols-2"><select name="competitor_id" class="rounded-xl border p-3"><option value="">Kompetitor terdaftar (atau isi manual)</option>@foreach($competitors as $c)<option value="{{ $c->id }}">{{ $c->code }} — {{ $c->name }}</option>@endforeach</select><input name="name" placeholder="Nama peserta (jika manual)" class="rounded-xl border p-3"></div><div class="grid gap-2 sm:grid-cols-4"><input type="number" step=".01" name="bid_value" placeholder="Nilai bid" class="rounded-xl border p-3"><input type="number" min="1" name="rank" placeholder="Rank" class="rounded-xl border p-3"><label class="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" name="is_winner" value="1"> Pemenang</label><button class="rounded-xl bg-violet-700 p-3 text-white font-bold">Catat</button></div></form>
</div>
<div class="mt-8 grid gap-6 lg:grid-cols-2"><form method="post" action="/admin/customers" class="grid gap-3 rounded-2xl border bg-white p-6">@csrf<h2 class="font-bold">Pelanggan baru</h2><input name="code" placeholder="Kode" required class="rounded-xl border p-3"><input name="name" placeholder="Nama pelanggan" required class="rounded-xl border p-3"><input name="payment_term_days" type="number" min="0" max="365" value="30" placeholder="Termin (hari)" class="rounded-xl border p-3" title="Termin pembayaran default untuk jatuh tempo tagihan"><button class="rounded-xl bg-slate-800 p-3 font-bold text-white">Simpan pelanggan</button></form><form method="post" action="/admin/tenders" class="grid gap-3 rounded-2xl border bg-white p-6">@csrf<h2 class="font-bold">Tender baru</h2><select name="customer_id" required class="rounded-xl border p-3"><option value="">Pilih pelanggan</option>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><input name="project_name" placeholder="Nama proyek" required class="rounded-xl border p-3"><input name="location" placeholder="Lokasi" class="rounded-xl border p-3"><input name="bid_value" type="number" min="0" step="0.01" placeholder="Nilai penawaran" class="rounded-xl border p-3"><button class="rounded-xl bg-sky-700 p-3 font-bold text-white">Simpan tender</button></form></div>
<div class="mt-8 flex flex-wrap items-center gap-2 no-print"><a href="/admin/tenders" @class(['rounded-xl border px-4 py-2 text-sm font-semibold', 'bg-sky-700 text-white' => !request('view'), 'bg-white' => request('view')])>Tabel</a><a href="/admin/tenders?view=kanban" @class(['rounded-xl border px-4 py-2 text-sm font-semibold', 'bg-sky-700 text-white' => request('view') === 'kanban', 'bg-white' => request('view') !== 'kanban'])>Kanban</a><span class="ml-auto text-xs font-bold uppercase tracking-wide text-slate-500">Status:</span>@foreach(['preparation' => 'Persiapan', 'bidding' => 'Bidding', 'won' => 'Menang', 'lost' => 'Kalah'] as $s => $label)<a href="/admin/tenders?status={{ $s }}{{ request('view') ? '&view='.request('view') : '' }}" @class(['rounded-full border px-3 py-1 text-xs font-semibold', 'bg-sky-100 text-sky-800 border-sky-300' => request('status') === $s, 'bg-white text-slate-600' => request('status') !== $s])>{{ $label }}</a>@endforeach @if(request('status'))<a href="/admin/tenders" class="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">Reset</a>@endif<form method="get" action="/admin/tenders" class="ml-2 flex items-center gap-1">@if(request('view'))<input type="hidden" name="view" value="{{ request('view') }}">@endif<input name="q" value="{{ request('q') }}" placeholder="Cari nomor/proyek..." class="w-44 rounded-full border px-3 py-1 text-xs">@if(request('status'))<input type="hidden" name="status" value="{{ request('status') }}">@endif<button class="rounded-full bg-slate-800 px-3 py-1 text-xs font-bold text-white">Cari</button></form></div>
@if($kanban)
<x-ui.kanban :columns="$kanban" class="mt-6" />
@else
<div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Nomor</th><th>Proyek</th><th>Pelanggan</th><th>Nilai</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($tenders as $t)<tr class="cursor-pointer hover:bg-slate-50 dark:hover:!bg-slate-800" onclick="location.href='/admin/tenders/{{ $t->id }}'"><td>{{ $t->number }}</td><td>{{ $t->project_name }}</td><td>{{ $t->customer->name }}</td><td>Rp {{ number_format((float)$t->bid_value,0,',','.') }}</td><td>{{ strtoupper($t->status) }}</td><td onclick="event.stopPropagation()">@if(!$t->outcome)<form method="post" action="/admin/tenders/{{ $t->id }}/outcome" class="flex gap-2">@csrf<input type="hidden" name="announced_at" value="{{ now()->toDateString() }}"><button name="outcome" value="won" class="text-emerald-700">Menang</button><button name="outcome" value="lost" class="text-red-700">Kalah</button></form>@elseif($t->status==='won')<form method="post" action="/admin/tenders/{{ $t->id }}/convert">@csrf<button class="text-sky-700">Konversi proyek</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="p-8 text-center">Belum ada tender.</td></tr>@endforelse</tbody></table></div>{{ $tenders->links() }}
@endif
</section></x-layouts.app>
