<x-layouts.app title="Inventory & Gudang"><section class="mx-auto max-w-7xl px-6 py-10"><h1 class="text-2xl font-bold tracking-tight">Inventory & Gudang</h1>@if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-4">{{ session('status') }}</div>@endif @if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif<div class="mt-8 grid gap-6 lg:grid-cols-2"><form method="post" action="/admin/inventory/setup" class="rounded-[var(--radius-card)] border bg-white p-6 shadow-[var(--shadow-card)]">@csrf
<x-ui.form-section title="Master Item & Gudang" description="Item baru + lokasi penyimpanan defaultnya.">
<div class="grid gap-4 sm:grid-cols-2"><x-ui.field label="SKU" name="sku" hint="Kode unik item" required><input name="sku" placeholder="mis. BESI-12" required class="w-full p-3"></x-ui.field><x-ui.field label="Nama barang" name="name" required><input name="name" placeholder="mis. Besi Beton 12mm" required class="w-full p-3"></x-ui.field><x-ui.field label="Kategori" name="category" required><input name="category" placeholder="mis. material" required class="w-full p-3"></x-ui.field><x-ui.field label="UOM" name="uom" hint="Satuan dasar (KG, UNIT, M3)" required><input name="uom" placeholder="KG" required class="w-full p-3"></x-ui.field><x-ui.field label="Kode gudang" name="warehouse_code" required><input name="warehouse_code" placeholder="W1" required class="w-full p-3"></x-ui.field><x-ui.field label="Nama gudang" name="warehouse_name" required><input name="warehouse_name" placeholder="Gudang Utama" required class="w-full p-3"></x-ui.field><x-ui.field label="Bin" name="bin_code" hint="Rak/lokasi fisik" required><input name="bin_code" placeholder="A1" required class="w-full p-3"></x-ui.field></div>
<div class="mt-4"><button class="rounded-xl bg-slate-800 p-3 font-bold text-white">Simpan master</button></div>
</x-ui.form-section>
</form><form method="post" action="/admin/inventory/movements" class="rounded-[var(--radius-card)] border bg-white p-6 shadow-[var(--shadow-card)]">@csrf
<x-ui.form-section title="Posting Movement" description="Semua pergerakan masuk stock ledger immutable dengan FIFO cost.">
<div class="grid gap-4 sm:grid-cols-2"><x-ui.field label="Item" name="item_id" required><select name="item_id" required class="w-full p-3">@foreach($items as $i)<option value="{{ $i->id }}">{{ $i->sku }} — {{ $i->name }}</option>@endforeach</select></x-ui.field><x-ui.field label="Gudang / Bin" name="warehouse_bin_id" required><select name="warehouse_bin_id" required class="w-full p-3">@foreach($warehouses as $w)@foreach($w->bins as $b)<option value="{{ $b->id }}">{{ $w->code }}/{{ $b->code }}</option>@endforeach @endforeach</select></x-ui.field><x-ui.field label="Jenis movement" name="movement_type"><select name="movement_type" class="w-full p-3"><option value="receipt">Penerimaan</option><option value="issue">Pengeluaran</option><option value="return_in">Pengembalian</option><option value="adjustment_in">Adjustment +</option><option value="adjustment_out">Adjustment -</option></select></x-ui.field><div class="grid grid-cols-2 gap-3"><x-ui.field label="Qty" name="quantity" required><input name="quantity" type="number" step=".0001" placeholder="0.0000" required class="w-full p-3"></x-ui.field><x-ui.field label="Unit cost" name="unit_cost" hint="Wajib untuk receipt"><input name="unit_cost" type="number" step=".0001" placeholder="0" class="w-full p-3"></x-ui.field></div><x-ui.field label="Referensi unik" name="reference_id" hint="Kunci idempotensi — duplikat ditolak" required><input name="reference_id" placeholder="mis. GR-2026-001" required class="w-full p-3"></x-ui.field><x-ui.field label="Alasan" name="reason" hint="Opsional, masuk audit"><input name="reason" placeholder="mis. terima dari PO-12" class="w-full p-3"></x-ui.field></div>
<div class="mt-4"><button class="rounded-xl bg-[var(--brand-primary)] p-3 font-bold text-white">Post movement</button></div>
</x-ui.form-section>
</form></div><a href="/admin/inventory/lots" class="mt-4 inline-block rounded-xl border px-4 py-2 text-sm font-semibold no-print hover:border-[var(--brand-primary)]">Telusuri Lot (traceability)</a><div class="mt-8 overflow-x-auto rounded-2xl border bg-white" id="stok-kritis">@if($lowStock->isNotEmpty())<div class="flex items-center gap-2 border-b border-amber-200 bg-amber-50 px-5 py-3"><span>âš ï¸</span><strong class="text-sm text-amber-800">Stok Kritis —” {{ $lowStock->count() }} baris di bawah minimum stock</strong></div>@endif<table class="w-full text-sm"><thead><tr><th>SKU</th><th>Gudang/Bin</th><th>Qty</th><th>Min. Stock</th><th>Status</th></tr></thead><tbody>@forelse($lowStock as $row)<tr><td>{{ $row->item->sku }} <span class="block text-xs text-slate-400">{{ $row->item->name }}</span></td><td>{{ $row->warehouse->code }}/{{ $row->bin?->code }}</td><td class="font-mono font-bold text-amber-700">{{ $row->quantity }}</td><td class="font-mono">{{ $row->item->minimum_stock }}</td><td><x-ui.badge status="exception" label="di bawah minimum" /></td></tr>@empty<tr><td colspan="5" class="p-6 text-center text-slate-500">Semua stok di atas minimum —” aman.</td></tr>@endforelse</tbody></table></div>
<x-ui.filter-bar action="/admin/inventory" class="mt-8 flex flex-wrap items-center gap-2">
<input name="q" value="{{ request('q') }}" placeholder="Cari SKU/nama item..." class="w-56 rounded-full border px-3 py-1 text-xs">
<x-ui.button variant="secondary" type="submit" class="!rounded-full !px-3 !py-1 !text-xs">Filter</x-ui.button>
<span class="text-xs text-slate-400">{{ $balanceCount }} baris saldo</span>
</x-ui.filter-bar>
<div class="mt-4 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm table-sticky"><thead><tr><th>SKU</th><th>Gudang/Bin</th><th>Lot</th><th>Qty</th><th>Reserved</th></tr></thead><tbody>@forelse($balances as $b)<tr><td>{{ $b->item->sku }}</td><td>{{ $b->warehouse->code }}/{{ $b->bin?->code }}</td><td>{{ $b->lot_number?:'-' }}</td><td>{{ $b->quantity }}</td><td>{{ $b->reserved_quantity }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center">Belum ada stok.</td></tr>@endforelse</tbody></table></div>{{ $balances->links() }}</section></x-layouts.app>
