<?php

use App\Http\Controllers\ApprovalController;
use App\Http\Controllers\AuditController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\CageController;
use App\Http\Controllers\CashBankController;
use App\Http\Controllers\CasingController;
use App\Http\Controllers\ContractAdminController;
use App\Http\Controllers\ContractController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\ExperienceController;
use App\Http\Controllers\FieldOpsController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\FixedAssetController;
use App\Http\Controllers\FuelTankController;
use App\Http\Controllers\GlobalSearchController;
use App\Http\Controllers\HseController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\ManufacturingController;
use App\Http\Controllers\MaterialRequestController;
use App\Http\Controllers\MyWorkController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\PileGenealogyController;
use App\Http\Controllers\PilePassportController;
use App\Http\Controllers\PileReadinessController;
use App\Http\Controllers\ProcurementController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProjectCostingController;
use App\Http\Controllers\ProjectFoundationController;
use App\Http\Controllers\ProjectHandoverController;
use App\Http\Controllers\QmsController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RfqController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SignatureController;
use App\Http\Controllers\SignatureImageController;
use App\Http\Controllers\StockOpnameController;
use App\Http\Controllers\StoredFileController;
use App\Http\Controllers\TaxController;
use App\Http\Controllers\TenderController;
use App\Http\Controllers\ToolController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome')->name('home');
Route::get('/piles/{publicUuid}', [PilePassportController::class, 'publicEntry'])->name('piles.public');
Route::get('/verify/{token}', [SignatureController::class, 'verify'])->name('signatures.verify');
Route::view('/docs', 'docs')->name('docs');
Route::view('/login', 'auth.login')->middleware('guest')->name('login');
Route::post('/login', function (Request $r) {
    $c = $r->validate(['email' => ['required', 'email'], 'password' => ['required']]);
    if (! Auth::attempt([...$c, 'is_active' => true])) {
        return back()->withErrors(['email' => 'Login tidak valid.']);
    }$r->session()->regenerate();

    return redirect('/dashboard');
})->middleware(['guest', 'throttle:5,1']);
Route::post('/logout', function (Request $r) {
    Auth::logout();
    $r->session()->invalidate();
    $r->session()->regenerateToken();

    return redirect('/');
})->middleware('auth');
Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth', 'company'])->name('dashboard');
Route::get('/apps', [WorkspaceController::class, 'apps'])->middleware(['auth', 'company'])->name('apps');
Route::get('/admin/my-work', [MyWorkController::class, 'index'])->middleware(['auth', 'company'])->name('my-work.index');
Route::post('/admin/preferences/favorites', [WorkspaceController::class, 'toggleFavorite'])->middleware(['auth', 'company'])->name('preferences.favorites.toggle');
Route::post('/admin/company/switch', [WorkspaceController::class, 'switchCompany'])->middleware(['auth'])->name('company.switch');
Route::post('/admin/preferences/recent', [WorkspaceController::class, 'recordRecent'])->middleware(['auth', 'company'])->withoutMiddleware(VerifyCsrfToken::class)->name('preferences.recent.record');
Route::get('/admin/search', [GlobalSearchController::class, 'query'])->middleware(['auth', 'company'])->name('global-search.query');
Route::middleware(['auth', 'company', 'permission:contract.view'])->prefix('admin/contracts')->group(function () {
    Route::get('/', [ContractController::class, 'index'])->name('contracts.index');
    Route::get('/{contract}', [ContractController::class, 'show'])->name('contracts.show');
    Route::post('/', [ContractController::class, 'store'])->middleware('permission:contract.manage')->name('contracts.store');
    Route::post('/{contract}/submit', [ContractController::class, 'submit'])->middleware('permission:contract.manage')->name('contracts.submit');
});
Route::middleware(['auth', 'company', 'permission:organization.view'])->prefix('admin')->group(function () {
    Route::get('/organization', [OrganizationController::class, 'index'])->name('organization.index');
    Route::get('/organization/roles', [OrganizationController::class, 'roles'])->name('organization.roles');
    Route::post('/organization/roles', [OrganizationController::class, 'storeRole'])->middleware('permission:organization.manage')->name('organization.roles.store');
    Route::post('/organization/roles/{role}/permissions', [OrganizationController::class, 'updatePermissions'])->middleware('permission:organization.manage')->name('organization.roles.permissions');
    Route::post('/organization/roles/{role}/members', [OrganizationController::class, 'attachMember'])->middleware('permission:organization.manage')->name('organization.roles.members.attach');
    Route::post('/organization/roles/{role}/members/{user}/detach', [OrganizationController::class, 'detachMember'])->middleware('permission:organization.manage')->name('organization.roles.members.detach');
    Route::post('/branches', [OrganizationController::class, 'storeBranch'])->middleware('permission:organization.manage')->name('branches.store');
    Route::post('/departments', [OrganizationController::class, 'storeDepartment'])->middleware('permission:organization.manage')->name('departments.store');
});
Route::middleware(['auth', 'company', 'permission:finance.view'])->prefix('admin')->group(function () {
    Route::get('/finance/overview', [FinanceController::class, 'overview'])->name('finance.overview');
    Route::get('/finance', [FinanceController::class, 'index'])->name('finance.index');
    Route::get('/finance/accounts', [FinanceController::class, 'accounts'])->name('finance.accounts');
    Route::get('/finance/periods', [FinanceController::class, 'periods'])->name('finance.periods');
    Route::get('/finance/journals', [FinanceController::class, 'journals'])->name('finance.journals');
    Route::get('/finance/accounting-mappings', [FinanceController::class, 'mappingIndex'])->name('finance.mappings');
    Route::post('/finance/accounts', [FinanceController::class, 'account'])->middleware('permission:finance.manage');
    Route::post('/finance/periods', [FinanceController::class, 'period'])->middleware('permission:finance.manage');
    Route::post('/finance/mappings', [FinanceController::class, 'mapping'])->middleware('permission:finance.manage');
    Route::post('/finance/journals', [FinanceController::class, 'journal'])->middleware('permission:accounting.post');
    Route::get('/recurring-journals', [FinanceController::class, 'recurringJournals'])->name('finance.recurring-journals');
    Route::post('/recurring-journals', [FinanceController::class, 'storeRecurringJournal'])->middleware('permission:finance.manage');
    Route::post('/recurring-journals/{recurring}/toggle', [FinanceController::class, 'toggleRecurringJournal'])->middleware('permission:finance.manage');
    Route::post('/recurring-journals/{recurring}/run', [FinanceController::class, 'runRecurringJournalNow'])->middleware('permission:accounting.post');
    Route::get('/account-budgets', [FinanceController::class, 'budgets'])->name('finance.account-budgets');
    Route::post('/account-budgets', [FinanceController::class, 'storeBudget'])->middleware('permission:finance.manage');
    Route::post('/account-budgets/{budget}/delete', [FinanceController::class, 'destroyBudget'])->middleware('permission:finance.manage');
    Route::get('/prepaid-expenses', [FinanceController::class, 'prepaids'])->name('finance.prepaids');
    Route::post('/prepaid-expenses', [FinanceController::class, 'storePrepaid'])->middleware('permission:finance.manage');
    Route::post('/prepaid-expenses/post-due', [FinanceController::class, 'postPrepaidDue'])->middleware('permission:accounting.post');
});
Route::middleware(['auth', 'company', 'permission:inventory.view'])->prefix('admin')->group(function () {
    Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory.index');
    Route::get('/inventory/opname', [StockOpnameController::class, 'index'])->name('opname.index');
    Route::get('/inventory/lots', [InventoryController::class, 'lotTrace'])->name('inventory.lot-trace');
    Route::get('/inventory/reorder', [InventoryController::class, 'reorder'])->name('inventory.reorder');
    Route::post('/inventory/items/{item}/reorder-settings', [InventoryController::class, 'updateReorderSettings'])->middleware('permission:inventory.manage');
    Route::post('/inventory/balances/{balance}/condition', [InventoryController::class, 'condition'])->middleware('permission:inventory.manage');
    Route::post('/inventory/balances-in-transit', [InventoryController::class, 'inTransit'])->middleware('permission:inventory.manage');
    Route::post('/inventory/opname', [StockOpnameController::class, 'store'])->middleware('permission:inventory.manage');
    Route::post('/inventory/opname/{count}/approve', [StockOpnameController::class, 'approve'])->middleware('permission:inventory.manage');
    Route::get('/inventory/material-requests', [MaterialRequestController::class, 'index'])->name('material-requests.index');
    Route::post('/inventory/material-requests', [MaterialRequestController::class, 'store'])->middleware('permission:inventory.manage');
    Route::post('/inventory/material-requests/{material_request}/approve', [MaterialRequestController::class, 'approve'])->middleware('permission:inventory.manage');
    Route::post('/inventory/material-requests/{material_request}/issue', [MaterialRequestController::class, 'issue'])->middleware('permission:inventory.manage');
    Route::post('/inventory/material-requests/{material_request}/lines/{line}/return', [MaterialRequestController::class, 'returnLine'])->middleware('permission:inventory.manage');
    Route::post('/inventory/setup', [InventoryController::class, 'setup'])->middleware('permission:inventory.manage');
    Route::post('/inventory/movements', [InventoryController::class, 'movement'])->middleware('permission:inventory.manage');
});
Route::middleware(['auth', 'company', 'permission:project.view'])->prefix('admin')->group(function () {
    Route::get('/projects', [ProjectController::class, 'index'])->name('projects.index');
    Route::get('/projects/field-ops', [FieldOpsController::class, 'index'])->name('field-ops.index');
    Route::get('/projects/{project}', [ProjectController::class, 'show'])->name('projects.show');
    Route::get('/projects/{project}/foundation-control', [ProjectFoundationController::class, 'show'])->name('projects.foundation-control');
    Route::post('/projects/field-ops/drillings', [FieldOpsController::class, 'storeDrilling'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/drillings/{drilling}/verify', [FieldOpsController::class, 'verifyDrilling'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/deliveries', [FieldOpsController::class, 'storeDelivery'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/deliveries/{delivery}/approve', [FieldOpsController::class, 'approveDelivery'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/deliveries/{delivery}/reject', [FieldOpsController::class, 'rejectDelivery'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/slurry', [FieldOpsController::class, 'storeSlurry'])->middleware('permission:project.manage')->name('field-ops.slurry.store');
    Route::post('/projects/field-ops/slurry/{slurryTest}/decide', [FieldOpsController::class, 'decideSlurry'])->middleware('permission:qms.verify')->name('field-ops.slurry.decide');
    Route::post('/projects/field-ops/tremie', [FieldOpsController::class, 'storeTremie'])->middleware('permission:project.manage')->name('field-ops.tremie.store');
    Route::post('/projects/field-ops/pour-intervals', [FieldOpsController::class, 'storePourInterval'])->middleware('permission:project.manage')->name('field-ops.pour-interval.store');
    Route::post('/projects/field-ops/geometry-import', [FieldOpsController::class, 'importGeometry'])->middleware('permission:project.manage')->name('field-ops.geometry.import');
    Route::post('/projects/field-ops/tests', [FieldOpsController::class, 'storeTest'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/tests/{test}/result', [FieldOpsController::class, 'recordTestResult'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/tests/{test}/approve', [FieldOpsController::class, 'approveTest'])->middleware('permission:project.manage');
    Route::post('/projects/field-ops/evidence/{type}', [FieldOpsController::class, 'uploadEvidence'])->middleware('permission:project.manage');
    Route::get('/field-evidence/{evidence}/download', [FieldOpsController::class, 'downloadEvidence'])->name('evidence.download');
    Route::get('/field-evidence/{evidence}/file', [FieldOpsController::class, 'fileEvidence'])->name('evidence.file');
    Route::get('/bored-piles/{pile}/genealogy', [PileGenealogyController::class, 'show'])->name('piles.genealogy');
    Route::get('/bored-piles/{pile}/passport', [PilePassportController::class, 'show'])->name('piles.passport');
    Route::post('/bored-piles/{pile}/readiness-check', [PileReadinessController::class, 'check'])->middleware('permission:project.manage')->name('piles.readiness.check');
    Route::post('/bored-piles/{pile}/attest', [PileReadinessController::class, 'attest'])->middleware('permission:project.manage')->name('piles.attest');
    Route::post('/bored-piles/{pile}/planned-date', [PileReadinessController::class, 'planDate'])->middleware('permission:project.manage')->name('piles.planned-date.update');
    Route::post('/bored-piles/{pile}/cleaning-inspections', [PileReadinessController::class, 'storeCleaning'])->middleware('permission:project.manage')->name('piles.cleaning.store');
    Route::post('/cleaning-inspections/{inspection}/decide', [PileReadinessController::class, 'decideCleaning'])->middleware('permission:qms.verify')->name('piles.cleaning.decide');
    Route::post('/bored-piles/{pile}/photos', [PilePassportController::class, 'uploadPhoto'])->middleware('permission:project.manage')->name('piles.photos.store');
    Route::post('/bored-piles/{pile}/as-built/store', [PilePassportController::class, 'storeAsBuilt'])->middleware('permission:project.manage')->name('piles.as-built.store');
    Route::post('/bored-piles/{pile}/dossier/store', [PilePassportController::class, 'storeDossier'])->middleware('permission:project.manage')->name('piles.dossier.store');
    Route::post('/bored-piles/{pile}/acceptance/request', [PilePassportController::class, 'requestAcceptance'])->middleware('permission:project.manage')->name('piles.acceptance.request');
    Route::post('/bored-piles/{pile}/acceptance/qa-review', [PilePassportController::class, 'reviewQa'])->middleware('permission:qms.verify')->name('piles.acceptance.qa');
    Route::post('/bored-piles/{pile}/acceptance/engineer-review', [PilePassportController::class, 'reviewEngineer'])->middleware('permission:approval.decide')->name('piles.acceptance.engineer');
    Route::post('/bored-piles/{pile}/acceptance/decide', [PilePassportController::class, 'decideAcceptance'])->middleware('permission:approval.decide')->name('piles.acceptance.decide');
    Route::get('/files/{file}/preview', [StoredFileController::class, 'preview'])->name('files.preview');
    Route::get('/files/{file}/download', [StoredFileController::class, 'download'])->name('files.download');
    Route::get('/bored-piles/{pile}/as-built', [PileGenealogyController::class, 'asBuilt'])->name('piles.as-built');
    Route::get('/projects/{project}/piles-as-built', [PileGenealogyController::class, 'batchAsBuilt'])->name('piles.as-built.batch');
    Route::post('/project-zones', [ProjectController::class, 'zone'])->middleware('permission:project.manage');
    Route::post('/bored-piles', [ProjectController::class, 'pile'])->middleware('permission:project.manage');
    Route::post('/bored-piles/{pile}/transition', [ProjectController::class, 'transition'])->middleware('permission:project.manage');
    Route::post('/bored-piles/{pile}/concrete', [ProjectController::class, 'concrete'])->middleware('permission:project.manage');
    Route::post('/projects/{project}/constraints', [ProjectController::class, 'storeConstraint'])->middleware('permission:project.manage');
    Route::post('/projects/{project}/handover-package', [ProjectHandoverController::class, 'build'])->name('projects.handover.build');
    Route::post('/constraints/{constraint}/status', [ProjectController::class, 'updateConstraintStatus'])->middleware('permission:project.manage');
    Route::post('/projects/{project}/wbs', [ProjectController::class, 'storeWbs'])->middleware('permission:project.manage');
    Route::post('/projects/{project}/procurement-plans', [ProjectController::class, 'storePlan'])->middleware('permission:procurement.manage');
    Route::post('/procurement-plans/{plan}/link', [ProjectController::class, 'linkPlanDocument'])->middleware('permission:procurement.manage');
});
Route::middleware(['auth', 'company', 'permission:contract.view'])->prefix('admin/contract-admin')->group(function () {
    Route::get('/', [ContractAdminController::class, 'index'])->name('contract-admin.index');
    Route::post('/{award}/milestones', [ContractAdminController::class, 'storeMilestone'])->middleware('permission:contract.manage');
    Route::post('/milestones/{milestone}/achieve', [ContractAdminController::class, 'achieveMilestone'])->middleware('permission:contract.manage');
    Route::post('/{award}/insurances', [ContractAdminController::class, 'storeInsurance'])->middleware('permission:contract.manage');
    Route::post('/{award}/correspondences', [ContractAdminController::class, 'storeCorrespondence'])->middleware('permission:contract.manage');
});
Route::middleware(['auth', 'company', 'permission:tender.view'])->prefix('admin')->group(function () {
    Route::get('/tenders', [TenderController::class, 'index'])->name('tenders.index');
    Route::get('/tenders/{tender}', [TenderController::class, 'show'])->name('tenders.show');
    Route::post('/customers', [TenderController::class, 'storeCustomer'])->middleware('permission:tender.manage');
    Route::post('/competitors', [TenderController::class, 'storeCompetitor'])->middleware('permission:tender.manage');
    Route::post('/participants', [TenderController::class, 'storeParticipant'])->middleware('permission:tender.manage');
    Route::post('/tenders', [TenderController::class, 'store'])->middleware('permission:tender.manage');
    Route::post('/tenders/{tender}/outcome', [TenderController::class, 'outcome'])->middleware('permission:tender.manage');
    Route::post('/tenders/{tender}/bid-decision', [TenderController::class, 'bidDecision'])->middleware('permission:tender.manage');
    Route::post('/tenders/{tender}/convert', [TenderController::class, 'convert'])->middleware('permission:tender.manage');
});
Route::middleware(['auth', 'company', 'permission:document.view'])->prefix('admin')->group(function () {
    Route::get('/documents', [DocumentController::class, 'index'])->name('documents.index');
    Route::get('/documents/transmittals', [DocumentController::class, 'transmittals'])->name('documents.transmittals');
    Route::post('/documents/transmittals', [DocumentController::class, 'storeTransmittal'])->middleware('permission:document.manage');
    Route::post('/documents/transmittals/{transmittal}/acknowledge', [DocumentController::class, 'acknowledgeTransmittal'])->middleware('permission:document.manage');
    Route::get('/documents/{document}', [DocumentController::class, 'show'])->name('documents.show');
    Route::post('/documents', [DocumentController::class, 'store'])->middleware('permission:document.manage')->name('documents.store');
    Route::get('/document-versions/{version}/download', [DocumentController::class, 'download'])->name('documents.download');
});
Route::middleware(['auth', 'company', 'permission:qms.view'])->prefix('admin')->group(function () {
    Route::get('/qms', [QmsController::class, 'index'])->name('qms.index');
    Route::get('/qms/ncrs/{ncr}', [QmsController::class, 'showNcr'])->name('qms.ncr-show');
    Route::post('/qms/risks', [QmsController::class, 'risk'])->middleware('permission:qms.manage');
    Route::post('/qms/ncrs', [QmsController::class, 'ncr'])->middleware('permission:qms.manage');
    Route::post('/qms/ncrs/{ncr}/actions', [QmsController::class, 'capa'])->middleware('permission:qms.manage');
    Route::post('/qms/actions/{action}/verify', [QmsController::class, 'verify'])->middleware('permission:qms.verify');
    Route::post('/qms/audits', [QmsController::class, 'audit'])->middleware('permission:qms.audit');
    Route::post('/qms/objectives', [QmsController::class, 'storeObjective'])->middleware('permission:qms.manage');
    Route::post('/qms/objectives/{objective}/actual', [QmsController::class, 'updateObjectiveActual'])->middleware('permission:qms.manage');
    Route::post('/qms/surveys', [QmsController::class, 'storeSurvey'])->middleware('permission:qms.manage');
    Route::get('/complaints', [QmsController::class, 'complaints'])->name('qms.complaints');
    Route::post('/complaints', [QmsController::class, 'storeComplaint'])->middleware('permission:qms.manage');
    Route::post('/complaints/{complaint}/resolve', [QmsController::class, 'resolveComplaint'])->middleware('permission:qms.manage');
    Route::post('/complaints/{complaint}/link-ncr', [QmsController::class, 'linkComplaintNcr'])->middleware('permission:qms.manage');
    Route::get('/itps', [QmsController::class, 'itps'])->name('qms.itps');
    Route::post('/itps', [QmsController::class, 'storeItp'])->middleware('permission:qms.manage');
    Route::post('/itp-items/{item}/inspections', [QmsController::class, 'storeInspection'])->middleware('permission:qms.manage');
    Route::post('/itps/{plan}/close', [QmsController::class, 'closeItp'])->middleware('permission:qms.manage');
});
Route::middleware(['auth', 'company', 'permission:report.view'])->prefix('admin/reports')->group(function () {
    Route::get('/executive', [ReportController::class, 'executive'])->name('reports.executive');
    Route::get('/finance', [ReportController::class, 'finance'])->name('reports.finance');
    Route::get('/operations', [ReportController::class, 'operations'])->name('reports.operations');
    Route::get('/manufacturing', [ReportController::class, 'manufacturing'])->name('reports.manufacturing');
    Route::get('/financial-statements', [ReportController::class, 'financialStatements'])->name('reports.financial-statements');
    Route::get('/cash-flow', [ReportController::class, 'cashFlow'])->name('reports.cash-flow');
    Route::get('/aging', [ReportController::class, 'aging'])->name('reports.aging');
    Route::get('/{type}/export', [ReportController::class, 'export'])->middleware('permission:report.export')->name('reports.export');
});
Route::middleware(['auth', 'company', 'permission:manufacturing.view'])->prefix('admin')->group(function () {
    Route::get('/manufacturing', [ManufacturingController::class, 'index'])->name('manufacturing.index');
    Route::get('/manufacturing/quality', [ManufacturingController::class, 'quality'])->name('manufacturing.quality');
    Route::get('/manufacturing/nonconforming', [ManufacturingController::class, 'nonconforming'])->name('manufacturing.nonconforming');
    Route::get('/manufacturing/costing', [ManufacturingController::class, 'costing'])->name('manufacturing.costing');
    Route::get('/manufacturing/cages', [CageController::class, 'index'])->name('cages.index');
    Route::get('/operations/equipment/{equipment}', [OperationsController::class, 'showEquipment'])->name('equipment.show');
    Route::get('/calibrations', [OperationsController::class, 'calibrations'])->name('calibrations.index');
    Route::post('/calibrations', [OperationsController::class, 'storeCalibration'])->middleware('permission:manufacturing.manage');
    Route::post('/operations/equipment/{equipment}/downtime', [OperationsController::class, 'startDowntime'])->middleware('permission:manufacturing.manage');
    Route::post('/operations/equipment/{equipment}/downtime/{log}/close', [OperationsController::class, 'closeDowntime'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/cages', [CageController::class, 'store'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/cages/{cage}/qc', [CageController::class, 'qc'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/cages/{cage}/deliver', [CageController::class, 'deliver'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/cages/{cage}/evidence', [CageController::class, 'uploadEvidence'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/cages/{cage}/material', [CageController::class, 'consumeMaterial'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/work-centers', [ManufacturingController::class, 'workCenter'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/boms/{bom}/routing-operations', [ManufacturingController::class, 'routingOperation'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/orders/{order}/operations/{operation}', [ManufacturingController::class, 'recordOperation'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/boms/{bom}/items', [ManufacturingController::class, 'addBomItem'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/orders/{order}/issue', [ManufacturingController::class, 'issue'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/orders/{order}/inspect', [ManufacturingController::class, 'inspect'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/inspections/{inspection}/dispose', [ManufacturingController::class, 'dispose'])->middleware('permission:manufacturing.manage');
    Route::get('/operations', [OperationsController::class, 'index'])->name('operations.index');
    Route::post('/manufacturing/boms', [OperationsController::class, 'bom'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/orders', [OperationsController::class, 'productionOrder'])->middleware('permission:manufacturing.manage');
    Route::post('/manufacturing/orders/{order}/complete', [OperationsController::class, 'complete'])->middleware('permission:manufacturing.manage');
    Route::post('/equipment', [OperationsController::class, 'equipment'])->middleware('permission:equipment.manage');
    Route::post('/equipment/{equipment}/meter', [OperationsController::class, 'meter'])->middleware('permission:equipment.manage');
    Route::post('/equipment/{equipment}/fuel', [OperationsController::class, 'fuel'])->middleware('permission:equipment.manage');
    Route::post('/equipment/{equipment}/maintenance', [OperationsController::class, 'maintenance'])->middleware('permission:equipment.manage');
    Route::post('/equipment/{equipment}/maintenance/{wo}/close', [OperationsController::class, 'closeMaintenance'])->middleware('permission:equipment.manage');
});
Route::middleware(['auth', 'company', 'permission:procurement.view'])->prefix('admin/procurement')->group(function () {
    Route::get('/', [ProcurementController::class, 'index'])->name('procurement.index');
    Route::get('/orders/{order}', [ProcurementController::class, 'showOrder'])->name('procurement.orders.show');
    Route::get('/rfq', [RfqController::class, 'index'])->name('rfq.index');
    Route::post('/rfq', [RfqController::class, 'store'])->middleware('permission:procurement.manage');
    Route::post('/rfq/{rfq}/invite', [RfqController::class, 'invite'])->middleware('permission:procurement.manage');
    Route::post('/rfq/{rfq}/quotations', [RfqController::class, 'submitQuotation'])->middleware('permission:procurement.manage');
    Route::post('/rfq/quotations/{quotation}/select', [RfqController::class, 'select'])->middleware('permission:procurement.manage');
    Route::post('/vendors', [ProcurementController::class, 'vendor'])->middleware('permission:procurement.manage');
    Route::post('/orders', [ProcurementController::class, 'order'])->middleware('permission:procurement.manage');
    Route::post('/orders/{order}/submit', [ProcurementController::class, 'submit'])->middleware('permission:procurement.manage');
    Route::post('/orders/{order}/activate', [ProcurementController::class, 'activate'])->middleware('permission:procurement.manage');
    Route::post('/orders/{order}/receive', [ProcurementController::class, 'receive'])->middleware('permission:inventory.manage');
    Route::post('/orders/{order}/invoice', [ProcurementController::class, 'invoice'])->middleware('permission:finance.manage');
    Route::post('/vendor-evaluations', [ProcurementController::class, 'storeEvaluation'])->middleware('permission:procurement.manage')->name('procurement.evaluations.store');
    Route::post('/vendors/{vendor}/status', [ProcurementController::class, 'setVendorStatus'])->middleware('permission:procurement.manage');
});
Route::get('/admin/procurement-accounting', [ProcurementController::class, 'accountingIndex'])->middleware(['auth', 'company', 'permission:accounting.post'])->name('procurement.accounting');
Route::post('/admin/procurement/receipts/{receipt}/post-accounting', [ProcurementController::class, 'postReceipt'])->middleware(['auth', 'company', 'permission:accounting.post']);
Route::post('/admin/procurement/invoices/{invoice}/post-accounting', [ProcurementController::class, 'postInvoice'])->middleware(['auth', 'company', 'permission:accounting.post']);
Route::middleware(['auth', 'company', 'permission:approval.view'])->prefix('admin/approvals')->group(function () {
    Route::get('/', [ApprovalController::class, 'index'])->name('approvals.index');
    Route::post('/workflows', [ApprovalController::class, 'workflow'])->middleware('permission:approval.manage');
    Route::post('/workflows/{workflow}/steps', [ApprovalController::class, 'step'])->middleware('permission:approval.manage');
    Route::post('/{approval}/decide', [ApprovalController::class, 'decide'])->middleware('permission:approval.decide');
    Route::post('/delegations', [ApprovalController::class, 'delegation'])->middleware('permission:approval.manage');
});
Route::middleware(['auth', 'company', 'permission:signature.view'])->prefix('admin/signatures')->group(function () {
    Route::get('/', [SignatureController::class, 'index'])->name('signatures.index');
    Route::post('/providers', [SignatureController::class, 'provider'])->middleware('permission:signature.manage');
    Route::post('/versions/{version}/internal', [SignatureController::class, 'internal'])->middleware('permission:signature.sign');
    Route::post('/batch-internal', [SignatureController::class, 'batchInternal'])->middleware('permission:signature.sign');
    Route::post('/versions/{version}/external', [SignatureController::class, 'external'])->middleware('permission:signature.manage');
});
Route::post('/webhooks/signatures/{provider}', [SignatureController::class, 'webhook'])->middleware('throttle:60,1')->name('signatures.webhook');
Route::middleware(['auth', 'company', 'permission:finance.view'])->prefix('admin/billing')->group(function () {
    Route::get('/', [BillingController::class, 'index'])->name('billing.index');
    Route::post('/', [BillingController::class, 'store'])->middleware('permission:finance.manage');
    Route::post('/{billing}/submit', [BillingController::class, 'submit'])->middleware('permission:finance.manage');
    Route::post('/{billing}/activate', [BillingController::class, 'activate'])->middleware('permission:finance.manage');
    Route::post('/{billing}/post', [BillingController::class, 'post'])->middleware('permission:accounting.post');
    Route::get('/{billing}/pdf', [BillingController::class, 'pdf'])->name('billing.pdf');
    Route::post('/retention-releases', [BillingController::class, 'storeRelease'])->middleware('permission:finance.manage');
    Route::post('/retention-releases/{release}/submit', [BillingController::class, 'submitRelease'])->middleware('permission:finance.manage');
    Route::post('/retention-releases/{release}/activate', [BillingController::class, 'activateRelease'])->middleware('permission:finance.manage');
    Route::post('/retention-releases/{release}/post', [BillingController::class, 'postRelease'])->middleware('permission:accounting.post');
    Route::post('/{billing}/credit-notes', [BillingController::class, 'creditNote'])->middleware('permission:accounting.post');
    Route::post('/{billing}/write-offs', [BillingController::class, 'requestWriteOff'])->middleware('permission:finance.manage');
    Route::post('/write-offs/{writeOff}/decide', [BillingController::class, 'decideWriteOff'])->middleware('permission:finance.manage');
});
Route::middleware(['auth', 'company', 'permission:finance.view'])->prefix('admin/cash-bank')->group(function () {
    Route::get('/', [CashBankController::class, 'index'])->name('cash-bank.index');
    Route::post('/accounts', [CashBankController::class, 'bank'])->middleware('permission:finance.manage');
    Route::post('/receipts', [CashBankController::class, 'receipt'])->middleware('permission:accounting.post');
    Route::post('/payments', [CashBankController::class, 'payment'])->middleware('permission:accounting.post');
    Route::post('/statements', [CashBankController::class, 'statement'])->middleware('permission:finance.manage');
    Route::post('/statements/{line}/reconcile', [CashBankController::class, 'reconcile'])->middleware('permission:finance.manage');
    Route::post('/periods/{period}/close', [CashBankController::class, 'close'])->middleware('permission:accounting.post');
});
Route::middleware(['auth', 'company', 'permission:finance.view'])->prefix('admin/taxes')->group(function () {
    Route::get('/', [TaxController::class, 'index'])->name('taxes.index');
    Route::post('/rates', [TaxController::class, 'storeRate'])->middleware('permission:finance.manage')->name('taxes.rates.store');
    Route::post('/rates/{rate}/toggle', [TaxController::class, 'toggleRate'])->middleware('permission:finance.manage')->name('taxes.rates.toggle');
});
Route::middleware(['auth', 'company', 'permission:finance.view'])->prefix('admin/project-costing')->group(function () {
    Route::get('/', [ProjectCostingController::class, 'index'])->name('project-costing.index');
    Route::post('/forecasts', [ProjectCostingController::class, 'forecast'])->middleware('permission:finance.manage');
    Route::post('/baselines', [ProjectCostingController::class, 'storeBaseline'])->middleware('permission:finance.manage');
    Route::post('/baselines/{baseline}/approve', [ProjectCostingController::class, 'approveBaseline'])->middleware('permission:accounting.post');
});
Route::middleware(['auth', 'company', 'permission:finance.view'])->prefix('admin/fixed-assets')->group(function () {
    Route::get('/', [FixedAssetController::class, 'index'])->name('fixed-assets.index');
    Route::post('/categories', [FixedAssetController::class, 'category'])->middleware('permission:finance.manage');
    Route::post('/', [FixedAssetController::class, 'asset'])->middleware('permission:finance.manage');
    Route::post('/{asset}/depreciate', [FixedAssetController::class, 'depreciate'])->middleware('permission:accounting.post');
    Route::post('/{asset}/dispose', [FixedAssetController::class, 'dispose'])->middleware('permission:accounting.post');
});
Route::middleware(['auth', 'company', 'permission:hse.view'])->prefix('admin/hse')->group(function () {
    Route::get('/metrics', [HseController::class, 'metrics'])->name('hse.metrics');
    Route::get('/', [HseController::class, 'index'])->name('hse.index');
    Route::post('/jsa', [HseController::class, 'jsa'])->middleware('permission:hse.manage');
    Route::post('/jsa/{jsa}/submit', [HseController::class, 'submitJsa'])->middleware('permission:hse.manage');
    Route::post('/jsa/{jsa}/activate', [HseController::class, 'activateJsa'])->middleware('permission:hse.manage');
    Route::post('/jsa/{jsa}/permits', [HseController::class, 'permit'])->middleware('permission:hse.manage');
    Route::post('/incidents', [HseController::class, 'incident'])->middleware('permission:hse.manage');
    Route::post('/incidents/{incident}/actions', [HseController::class, 'action'])->middleware('permission:hse.manage');
    Route::post('/actions/{action}/verify', [HseController::class, 'verify'])->middleware('permission:hse.verify');
    Route::post('/incidents/{incident}/close', [HseController::class, 'close'])->middleware('permission:hse.verify');
    Route::post('/management-reviews', [HseController::class, 'review'])->middleware('permission:hse.manage');
    Route::post('/observations', [HseController::class, 'storeObservation'])->middleware('permission:hse.manage');
    Route::post('/observations/{observation}/resolve', [HseController::class, 'resolveObservation'])->middleware('permission:hse.verify');
    Route::post('/ppe', [HseController::class, 'issuePpe'])->middleware('permission:hse.manage');
    Route::post('/ppe/{issuance}/return', [HseController::class, 'returnPpe'])->middleware('permission:hse.manage');
    Route::post('/exposure-logs', [HseController::class, 'storeExposure'])->middleware('permission:hse.manage');
});
Route::middleware(['auth', 'company'])->prefix('admin/notifications')->group(function () {
    Route::get('/', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::post('/read-all', [NotificationController::class, 'readAll'])->name('notifications.readAll');
});
Route::get('/admin/audit', [AuditController::class, 'index'])->middleware(['auth', 'company', 'permission:audit.view'])->name('audit.index');
Route::get('/admin/fuel-tanks', [FuelTankController::class, 'index'])->middleware(['auth', 'company', 'permission:equipment.view'])->name('fuel-tanks.index');
Route::post('/admin/fuel-tanks', [FuelTankController::class, 'store'])->middleware(['auth', 'company', 'permission:equipment.manage']);
Route::post('/admin/fuel-tanks/{tank}/record', [FuelTankController::class, 'record'])->middleware(['auth', 'company', 'permission:equipment.manage']);
Route::post('/admin/fuel-tanks/{tank}/reconcile', [FuelTankController::class, 'reconcile'])->middleware(['auth', 'company', 'permission:equipment.manage']);
Route::get('/admin/my-signature', [SignatureImageController::class, 'page'])->middleware(['auth'])->name('signature-image.page');
Route::get('/admin/my-signature/image', [SignatureImageController::class, 'image'])->middleware(['auth'])->name('signature-image.image');
Route::post('/admin/my-signature', [SignatureImageController::class, 'upload'])->middleware(['auth'])->name('signature-image.upload');
Route::get('/admin/casings', [CasingController::class, 'index'])->middleware(['auth', 'company', 'permission:equipment.view'])->name('casings.index');
Route::post('/admin/casings', [CasingController::class, 'store'])->middleware(['auth', 'company', 'permission:equipment.manage']);
Route::post('/admin/casings/{casing}/move', [CasingController::class, 'move'])->middleware(['auth', 'company', 'permission:equipment.manage']);
Route::post('/admin/casings/{casing}/evidence', [CasingController::class, 'uploadEvidence'])->middleware(['auth', 'company', 'permission:equipment.manage']);
Route::get('/admin/tools', [ToolController::class, 'index'])->middleware(['auth', 'company', 'permission:inventory.view'])->name('tools.index');
Route::post('/admin/tools', [ToolController::class, 'store'])->middleware(['auth', 'company', 'permission:inventory.manage']);
Route::post('/admin/tools/{tool}/checkout', [ToolController::class, 'checkOut'])->middleware(['auth', 'company', 'permission:inventory.manage']);
Route::post('/admin/tools/{tool}/checkin', [ToolController::class, 'checkIn'])->middleware(['auth', 'company', 'permission:inventory.manage']);
Route::post('/admin/tools/{tool}/lost', [ToolController::class, 'markLost'])->middleware(['auth', 'company', 'permission:inventory.manage']);
Route::post('/admin/tools/{tool}/evidence', [ToolController::class, 'uploadEvidence'])->middleware(['auth', 'company', 'permission:inventory.manage']);
Route::get('/branding/{company}/{file}', [ExperienceController::class, 'serveAsset'])->name('branding.asset');
Route::get('/admin/experience', [ExperienceController::class, 'edit'])->middleware(['auth', 'company'])->name('experience.studio');
Route::post('/admin/experience', [ExperienceController::class, 'update'])->middleware(['auth', 'company'])->name('experience.update');
Route::post('/admin/experience/draft', [ExperienceController::class, 'saveDraft'])->middleware(['auth', 'company']);
Route::post('/admin/experience/versions/{version}/publish', [ExperienceController::class, 'publishVersion'])->middleware(['auth', 'company']);
Route::post('/admin/experience/versions/{version}/rollback', [ExperienceController::class, 'rollbackTo'])->middleware(['auth', 'company']);
Route::post('/admin/experience/assets', [ExperienceController::class, 'uploadAsset'])->middleware(['auth', 'company']);
Route::post('/admin/experience/launcher', [ExperienceController::class, 'saveLauncherConfig'])->middleware(['auth', 'company']);
Route::post('/admin/experience/public-site', [ExperienceController::class, 'savePublicSite'])->middleware(['auth', 'company']);
Route::post('/admin/experience/public-site/hero', [ExperienceController::class, 'uploadPublicHero'])->middleware(['auth', 'company']);
Route::post('/admin/experience/launcher/covers', [ExperienceController::class, 'uploadLauncherCover'])->middleware(['auth', 'company']);
Route::post('/admin/experience/launcher/covers/delete', [ExperienceController::class, 'deleteLauncherCover'])->middleware(['auth', 'company']);
Route::post('/admin/experience/versions/{version}/preview', [ExperienceController::class, 'startPreview'])->middleware(['auth', 'company']);
Route::post('/admin/experience/preview/stop', [ExperienceController::class, 'stopPreview'])->middleware(['auth', 'company']);
Route::get('/admin/experience/export', [ExperienceController::class, 'export'])->middleware(['auth', 'company']);
Route::post('/admin/experience/import', [ExperienceController::class, 'import'])->middleware(['auth', 'company']);
Route::get('/admin/settings', [SettingsController::class, 'index'])->middleware(['auth', 'company'])->name('settings.index');
Route::post('/admin/settings', [SettingsController::class, 'save'])->middleware(['auth', 'company', 'permission:finance.manage'])->name('settings.save');
