<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $title??config('app.name') }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
@auth
<div class="min-h-screen lg:grid lg:grid-cols-[270px_1fr]">
<aside id="admin-sidebar" class="fixed inset-y-0 left-0 z-40 w-[280px] -translate-x-full overflow-y-auto bg-slate-950 text-slate-200 shadow-2xl transition-transform lg:sticky lg:top-0 lg:h-screen lg:w-auto lg:translate-x-0">
 <div class="flex items-center justify-between border-b border-white/10 px-5 py-5"><a href="/dashboard" class="font-black text-white">Graha Pondasi ERP</a><button data-sidebar-close class="rounded-lg p-2 lg:hidden" aria-label="Tutup menu">✕</button></div>
 <nav class="space-y-6 p-4 text-sm">
  <div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Dashboard</p><a href="/dashboard" class="admin-link {{ request()->is('dashboard')?'active':'' }}"><span>▦</span> Executive Dashboard</a></div>
  @php($cid=session('company_id'))
  @if(auth()->user()->hasPermission('organization.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Organisasi</p><a href="/admin/organization" class="admin-link {{ request()->is('admin/organization')?'active':'' }}"><span>⌂</span> Perusahaan & Cabang</a></div>@endif
  @if(auth()->user()->hasPermission('tender.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Marketing & Tender</p><a href="/admin/tenders" class="admin-link {{ request()->is('admin/tenders*')?'active':'' }}"><span>◎</span> Pelanggan & Tender</a></div>@endif
  @if(auth()->user()->hasPermission('project.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Project & Bored Pile</p><a href="/admin/projects" class="admin-link {{ request()->is('admin/projects*')?'active':'' }}"><span>⌖</span> Proyek & Titik Bored Pile</a></div>@endif
  @if(auth()->user()->hasPermission('inventory.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Supply Chain</p><a href="/admin/inventory" class="admin-link {{ request()->is('admin/inventory*')?'active':'' }}"><span>▣</span> Inventory & Gudang</a></div>@endif
  @if(auth()->user()->hasPermission('procurement.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Procurement</p><a href="/admin/procurement" class="admin-link {{ request()->is('admin/procurement*')?'active':'' }}"><span>⌑</span> Vendor, PO & Receipt</a></div>@endif
  @if(auth()->user()->hasPermission('manufacturing.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Engineering & Workshop</p><a href="/admin/operations" class="admin-link {{ request()->is('admin/operations*')?'active':'' }}"><span>⚙</span> Produksi & Equipment</a></div>@endif
  @if(auth()->user()->hasPermission('finance.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Finance & Accounting</p><a href="/admin/finance" class="admin-link {{ request()->is('admin/finance*')?'active':'' }}"><span>◫</span> COA & General Ledger</a></div>@endif
  @if(auth()->user()->hasPermission('finance.manage',$cid))<a href="/admin/finance/accounting-mappings" class="admin-link {{ request()->is('admin/finance/accounting-mappings')?'active':'' }}"><span>⇄</span> Accounting Mapping</a>@endif
  @if(auth()->user()->hasPermission('accounting.post',$cid))<a href="/admin/procurement-accounting" class="admin-link {{ request()->is('admin/procurement-accounting')?'active':'' }}"><span>₿</span> Procurement Posting</a>@endif
  @if(auth()->user()->hasPermission('document.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Governance</p><a href="/admin/documents" class="admin-link {{ request()->is('admin/documents*')?'active':'' }}"><span>▤</span> Document Control</a></div>@endif
  @if(auth()->user()->hasPermission('approval.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Approval & Signing</p><a href="/admin/approvals" class="admin-link {{ request()->is('admin/approvals*')?'active':'' }}"><span>✓</span> Inbox & Workflow</a></div>@endif
  @if(auth()->user()->hasPermission('qms.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Quality, HSE & ISO</p><a href="/admin/qms" class="admin-link {{ request()->is('admin/qms*')?'active':'' }}"><span>✓</span> Risiko, NCR & Audit</a></div>@endif
  @if(auth()->user()->hasPermission('report.view',$cid))<div><p class="px-3 text-[11px] font-bold uppercase tracking-widest text-slate-500">Laporan</p><a href="/admin/reports/executive" class="admin-link {{ request()->is('admin/reports/executive*')?'active':'' }}"><span>▥</span> Bisnis & Tender</a><a href="/admin/reports/finance" class="admin-link {{ request()->is('admin/reports/finance*')?'active':'' }}"><span>◩</span> Keuangan</a><a href="/admin/reports/operations" class="admin-link {{ request()->is('admin/reports/operations*')?'active':'' }}"><span>▦</span> Operasional</a></div>@endif
 </nav>
</aside>
<div id="sidebar-overlay" data-sidebar-close class="fixed inset-0 z-30 hidden bg-slate-950/60 lg:hidden"></div>
<div class="min-w-0"><header class="sticky top-0 z-20 flex items-center justify-between border-b bg-white/90 px-4 py-3 backdrop-blur lg:px-8"><div class="flex items-center gap-3"><button data-sidebar-open class="rounded-xl border p-2 lg:hidden" aria-label="Buka menu">☰</button><div><p class="text-xs text-slate-500">{{ session('company_id') ? \App\Models\Company::find(session('company_id'))?->name : '' }}</p><strong>{{ $title??'Dashboard' }}</strong></div></div><div class="flex items-center gap-4"><a href="/docs" class="text-sm">Dokumentasi</a><form method="post" action="/logout">@csrf<button class="rounded-xl border px-4 py-2 text-sm font-semibold">Keluar</button></form></div></header><main>{{ $slot }}</main></div>
</div>
@else
<header class="sticky top-0 z-20 border-b bg-white/90 backdrop-blur"><nav class="mx-auto flex max-w-7xl justify-between px-5 py-4"><a href="/" class="font-black text-sky-800">Graha Pondasi ERP</a><div class="flex gap-4"><a href="/docs">Dokumentasi</a><a href="/login">Masuk</a></div></nav></header><main>{{ $slot }}</main>
@endauth
</body></html>
