<x-layouts.app title="Quality, HSE & ISO">
<section class="mx-auto max-w-7xl px-4 py-8 sm:px-6">
 <h1 class="text-3xl font-black">Quality, HSE & ISO</h1><p class="mt-2 text-slate-500">Dukungan implementasi QMS—bukan klaim sertifikasi ISO.</p>
 @if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('status') }}</div>@endif
 @if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
 <div class="mt-8 grid gap-5 lg:grid-cols-3">
  <form method="post" action="/admin/qms/risks" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf<h2 class="font-bold">Risk & Opportunity</h2><input name="code" required placeholder="Kode" class="rounded-xl border p-3"><select name="type" class="rounded-xl border p-3"><option value="risk">Risiko</option><option value="opportunity">Peluang</option></select><input name="title" required placeholder="Judul" class="rounded-xl border p-3"><textarea name="description" required placeholder="Deskripsi" class="rounded-xl border p-3"></textarea><div class="grid grid-cols-2 gap-2"><input type="number" min="1" max="5" name="likelihood" required placeholder="Likelihood 1-5" class="rounded-xl border p-3"><input type="number" min="1" max="5" name="impact" required placeholder="Impact 1-5" class="rounded-xl border p-3"></div><select name="owner_id" required class="rounded-xl border p-3"><option value="">Owner</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><button class="rounded-xl bg-sky-700 p-3 text-white">Simpan & hitung skor</button></form>
  <form method="post" action="/admin/qms/ncrs" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf<h2 class="font-bold">Nonconformity (NCR)</h2><input name="number" required placeholder="Nomor NCR" class="rounded-xl border p-3"><input name="source_type" required placeholder="Sumber: inspection/audit" class="rounded-xl border p-3"><select name="severity" class="rounded-xl border p-3"><option value="minor">Minor</option><option value="major">Major</option><option value="observation">Observasi</option></select><textarea name="description" required placeholder="Ketidaksesuaian" class="rounded-xl border p-3"></textarea><textarea name="containment" placeholder="Containment" class="rounded-xl border p-3"></textarea><input type="date" name="due_at" class="rounded-xl border p-3"><button class="rounded-xl bg-amber-600 p-3 text-white">Catat NCR</button></form>
  <form method="post" action="/admin/qms/audits" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf<h2 class="font-bold">Jadwal Audit Internal</h2><input name="number" required placeholder="Nomor audit" class="rounded-xl border p-3"><input name="scope" required placeholder="Ruang lingkup" class="rounded-xl border p-3"><input name="criteria" required placeholder="Kriteria" class="rounded-xl border p-3"><select name="department_id" required class="rounded-xl border p-3"><option value="">Departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select name="auditor_id" required class="rounded-xl border p-3"><option value="">Auditor</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><select name="auditee_id" required class="rounded-xl border p-3"><option value="">Auditee</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><input type="date" name="scheduled_at" required class="rounded-xl border p-3"><button class="rounded-xl bg-slate-800 p-3 text-white">Jadwalkan audit</button></form>
 </div>
 <div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Kode</th><th>Jenis</th><th>Judul</th><th>Skor</th><th>Status</th></tr></thead><tbody>@forelse($risks as $risk)<tr><td>{{ $risk->code }}</td><td>{{ strtoupper($risk->type) }}</td><td>{{ $risk->title }}</td><td>{{ $risk->inherent_score }}</td><td>{{ $risk->status }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center">Belum ada risiko/peluang.</td></tr>@endforelse</tbody></table></div>
 <div class="mt-8 space-y-4"><h2 class="text-xl font-bold">NCR & CAPA</h2>@forelse($ncrs as $ncr)<article class="rounded-2xl border bg-white p-5"><div class="flex flex-wrap justify-between gap-3"><strong>{{ $ncr->number }} · {{ strtoupper($ncr->severity) }}</strong><span>{{ strtoupper($ncr->status) }}</span></div><p class="mt-2">{{ $ncr->description }}</p><form method="post" action="/admin/qms/ncrs/{{ $ncr->id }}/actions" class="mt-4 grid gap-2 md:grid-cols-4">@csrf<input name="action" required placeholder="Corrective action" class="rounded-xl border p-3"><select name="owner_id" required class="rounded-xl border p-3"><option value="">PIC</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><input type="date" name="due_at" required class="rounded-xl border p-3"><button class="rounded-xl bg-slate-800 p-3 text-white">Tambah CAPA</button></form>@foreach($ncr->actions as $action)<form method="post" action="/admin/qms/actions/{{ $action->id }}/verify" class="mt-3 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-4">@csrf<div>{{ $action->action }}<br><small>{{ strtoupper($action->status) }}</small></div><input name="evidence" value="{{ $action->evidence }}" placeholder="Referensi evidence" class="rounded-xl border p-3"><input name="effectiveness_notes" required placeholder="Catatan efektivitas" class="rounded-xl border p-3"><button class="rounded-xl bg-emerald-700 p-3 text-white">Verifikasi independen</button></form>@endforeach</article>@empty<p>Belum ada NCR.</p>@endforelse</div>
 <div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Nomor Audit</th><th>Ruang Lingkup</th><th>Jadwal</th><th>Status</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ $audit->number }}</td><td>{{ $audit->scope }}</td><td>{{ $audit->scheduled_at }}</td><td>{{ strtoupper($audit->status) }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center">Belum ada audit.</td></tr>@endforelse</tbody></table></div>
</section></x-layouts.app>
