<x-layouts.app title="Laporan Rekonsiliasi WIP Manufaktur">
<div class="page-container">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-widest text-[var(--brand-primary)]">Manufacturing Accounting</p><h1 class="mt-1 text-2xl font-bold tracking-tight">Rekonsiliasi WIP dan Biaya Produksi</h1><p class="mt-2 max-w-3xl text-slate-500">Snapshot saldo biaya setiap production order: biaya aktual harus dapat dijelaskan sebagai barang jadi, scrap, atau pekerjaan yang masih berlangsung. Order terminal dengan residual WIP ditandai sebagai anomali dan memblokir period closing.</p></div>@if(auth()->user()->hasPermission('report.export',app(\App\Support\Tenancy\CurrentCompany::class)->id()))<a href="/admin/reports/manufacturing/export?from={{ $from->toDateString() }}&to={{ $to->toDateString() }}" class="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Export CSV Rekonsiliasi</a>@endif</div>
    <div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><x-ui.card><p class="text-sm text-slate-500">Production Order</p><p class="mt-2 text-2xl font-bold tracking-tight">{{ $rows->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-slate-500">Total Biaya Aktual</p><p class="mt-2 text-2xl font-black">Rp {{ number_format((float)$totalActual,2,',','.') }}</p></x-ui.card><x-ui.card><p class="text-sm text-slate-500">Residual WIP</p><p class="mt-2 text-2xl font-black">Rp {{ number_format((float)$totalWip,2,',','.') }}</p></x-ui.card><article class="rounded-2xl border {{ $anomalies?'border-red-300 bg-red-50':'border-emerald-200 bg-emerald-50' }} p-5"><p class="text-sm text-slate-600">Anomali Terminal</p><p class="mt-2 text-2xl font-bold tracking-tight">{{ $anomalies }}</p></article></div>
    @if($rows->isEmpty())<div class="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><strong>Belum ada Production Order.</strong> Rekonsiliasi WIP belum dapat menghasilkan biaya produksi karena database belum memiliki production order. Data manufaktur yang tersedia ditampilkan pada tabel Cage Fabrication di bawah ini.</div>@endif
    <div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Production Order</th><th>Produk</th><th>Qty Rencana</th><th>Qty Dipertanggungjawabkan</th><th>Biaya Aktual</th><th>Barang Jadi</th><th>Scrap</th><th>Residual WIP</th><th>Rekonsiliasi</th></tr></thead><tbody>@forelse($rows as $row)<tr><td class="font-bold">{{ $row['order']->number }}</td><td>{{ $row['order']->bom?->outputItem?->name }}</td><td>{{ $row['order']->planned_quantity }}</td><td>{{ $row['accounted_quantity'] }}</td><td>Rp {{ number_format((float)$row['actual_cost'],2,',','.') }}</td><td>Rp {{ number_format((float)$row['completed_cost'],2,',','.') }}</td><td>Rp {{ number_format((float)$row['scrapped_cost'],2,',','.') }}</td><td class="font-bold">Rp {{ number_format((float)$row['residual_wip'],2,',','.') }}</td><td><span class="rounded-lg px-2 py-1 text-xs font-bold {{ $row['anomaly']?'bg-red-100 text-red-700':($row['terminal']?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700') }}">{{ $row['anomaly']?'ANOMALI':($row['terminal']?'RECONCILED':'WIP AKTIF') }}</span></td></tr>@empty<tr><td colspan="9" class="p-8 text-center text-slate-500">Belum ada production order untuk direkonsiliasi.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><div class="border-b px-5 py-4"><h2 class="text-lg font-black">Cage Fabrication</h2><p class="mt-1 text-sm text-slate-500">Data cage aktual dari perusahaan aktif; tidak dicampur sebagai biaya WIP production order.</p></div><table class="w-full text-sm"><thead><tr><th>Nomor Cage</th><th>Proyek / Pile</th><th>Berat Teoretis</th><th>Berat Aktual</th><th>QC</th><th>Dikirim</th></tr></thead><tbody>@forelse($cages as $cage)<tr><td class="font-bold font-mono">{{ $cage->number }}</td><td>{{ $cage->pile?->project?->code ?? '-' }}{{ $cage->pile?->code ? ' / '.$cage->pile->code : '' }}</td><td>{{ number_format((float) $cage->theoretical_weight_kg, 2, ',', '.') }} kg</td><td>{{ $cage->actual_weight_kg !== null ? number_format((float) $cage->actual_weight_kg, 2, ',', '.').' kg' : '-' }}</td><td><span class="rounded-lg px-2 py-1 text-xs font-bold {{ $cage->qc_status === 'passed' ? 'bg-emerald-100 text-emerald-700' : ($cage->qc_status === 'failed' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700') }}">{{ strtoupper($cage->qc_status) }}</span></td><td>{{ $cage->delivered_at?->format('d/m/Y') ?? 'Belum dikirim' }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada cage fabrication.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-5 rounded-2xl border bg-slate-50 p-5 text-sm text-slate-600"><strong>Interpretasi:</strong> WIP aktif boleh memiliki residual karena proses belum selesai. Status ANOMALI hanya muncul ketika seluruh kuantitas sudah menjadi barang jadi/scrap tetapi masih ada biaya tersisa atau alokasi berlebih.</div>
</div>
</x-layouts.app>
