<x-layouts.app title="Progress Billing & Retensi"><div class="page-container"><x-ui.page-header title="Progress Billing & Retensi" />
<div class="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4">
<x-ui.stat-card label="Total Billing" value="{{ number_format($billings->count()) }}" icon="receipt" tone="brand" :value-class="'text-[24px] leading-tight'" />
<x-ui.stat-card label="Posted" value="{{ number_format($billings->where('status', 'posted')->count()) }}" icon="check" tone="success" :value-class="'text-[24px] leading-tight'" />
<x-ui.stat-card label="Menunggu Proses" value="{{ number_format($billings->whereIn('status', ['draft', 'pending_approval'])->count()) }}" icon="clock" tone="warning" :value-class="'text-[24px] leading-tight'" />
<x-ui.stat-card label="DPP Posted" value="Rp {{ number_format((float) $billings->where('status', 'posted')->sum('gross_amount'), 0, ',', '.') }}" icon="banknote" tone="info" :value-class="'text-[18px] leading-tight'" />
</div>
<p class="mt-2 text-slate-500">Contract cap, approval gate, advance recovery, dan balanced AR posting.</p><button type="button" class="btn-brand inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="billing-create-drawer" aria-haspopup="dialog"><x-ui.icon name="plus" class="h-4 w-4" />Progress Billing</button>
@if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-4">{{ session('status') }}</div>@endif @if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
@if(auth()->user()->hasPermission('finance.manage',app(\App\Support\Tenancy\CurrentCompany::class)->id()))<div class="mt-8 grid gap-5 lg:grid-cols-2"><div class="rounded-2xl border bg-white p-5"><h2 class="font-bold">Progress Billing Accounting Mapping</h2><form method="post" action="/admin/finance/mappings" class="mt-3 grid gap-3">@csrf<input type="hidden" name="event_type" value="progress_billing"><select name="entry_side" class="rounded-xl border p-3"><option value="ar_debit">AR Debit</option><option value="retention_debit">Retention Receivable Debit</option><option value="advance_debit">Advance Liability Debit</option><option value="revenue_credit">Project Revenue Credit</option><option value="tax_credit">PPN Keluaran Credit</option></select><select name="account_id" required class="rounded-xl border p-3">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select><button class="rounded-xl bg-violet-700 p-3 text-white">Simpan mapping</button></form><div class="mt-4 space-y-2">@foreach($mappings as $mapping)<p class="rounded-lg bg-slate-50 p-2 text-sm">{{ $mapping->entry_side }} → {{ $mapping->account?->code }}</p>@endforeach</div></div></div>@endif
<div class="mt-10 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Nomor</th><th>Proyek</th><th>DPP</th><th>PPN</th><th>Total Tagihan</th><th>Retensi</th><th>Advance</th><th>Net AR</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($billings as $billing)<tr><td>{{ $billing->number }}</td><td>{{ $billing->project?->code }}</td><td>{{ $billing->gross_amount }}</td><td>{{ $billing->tax_amount }}</td><td class="font-semibold">{{ number_format(bcadd(bcadd((string) $billing->gross_amount, (string) $billing->tax_amount, 2), '0', 2), 2, ',', '.') }}</td><td>{{ $billing->retention_amount }}</td><td>{{ $billing->advance_recovery }}</td><td>{{ $billing->net_receivable }}</td><td>{{ strtoupper($billing->status) }}</td><td class="min-w-64">@if($billing->status==='draft')<form method="post" action="/admin/billing/{{ $billing->id }}/submit" class="flex gap-2">@csrf<select name="workflow_id" required class="min-w-0 flex-1 rounded-lg border p-2">@foreach(($workflows['progress_billing']??[]) as $workflow)<option value="{{ $workflow->id }}">{{ $workflow->name }}</option>@endforeach</select><input type="hidden" name="idempotency_key" value="billing-submit-{{ $billing->id }}"><button class="font-bold text-[var(--brand-primary)]">Submit</button></form>@elseif($billing->status==='pending_approval')<form method="post" action="/admin/billing/{{ $billing->id }}/activate">@csrf<button class="font-bold text-emerald-700">Validasi approval</button></form>@elseif($billing->status==='approved' && auth()->user()->hasPermission('accounting.post',app(\App\Support\Tenancy\CurrentCompany::class)->id()))<form method="post" action="/admin/billing/{{ $billing->id }}/post">@csrf<button class="font-bold text-violet-700">Post AR</button></form>@elseif($billing->status==='posted')<span class="font-mono">{{ $billing->journal?->number }}</span> <a href="/admin/billing/{{ $billing->id }}/pdf" class="ml-2 rounded-lg bg-slate-900 px-2.5 py-1 text-xs font-bold text-white no-print">PDF</a> <a href="/admin/billing/{{ $billing->id }}/pdf?format=thermal" target="_blank" class="ml-1 rounded-lg border px-2.5 py-1 text-xs font-bold no-print">Struk 80mm</a>@endif</td></tr>@empty<tr><td colspan="10" class="p-8 text-center">Belum ada progress billing.</td></tr>@endforelse</tbody></table></div>
<div class="mt-10 grid gap-5 lg:grid-cols-2"><form method="post" action="/admin/finance/mappings" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf<h2 class="font-bold">Mapping Release Retensi</h2><input type="hidden" name="event_type" value="retention_release"><select name="entry_side" class="rounded-xl border p-3"><option value="ar_debit">AR Debit</option><option value="retention_credit">Retention Receivable Credit</option></select><select name="account_id" required class="rounded-xl border p-3">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select><button class="rounded-xl bg-violet-700 p-3 text-white">Simpan mapping</button></form></div>
<div class="mt-6 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-sm"><thead><tr><th>Nomor Release</th><th>Proyek</th><th>Tanggal</th><th>Nilai</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($releases as $release)<tr><td>{{ $release->number }}</td><td>{{ $release->project?->code }}</td><td>{{ $release->release_date->format('d/m/Y') }}</td><td>{{ $release->amount }}</td><td>{{ strtoupper($release->status) }}</td><td>@if($release->status==='draft')<form method="post" action="/admin/billing/retention-releases/{{ $release->id }}/submit" class="flex gap-2">@csrf<select name="workflow_id" required class="rounded border p-2">@foreach(($workflows['retention_release']??[]) as $workflow)<option value="{{ $workflow->id }}">{{ $workflow->name }}</option>@endforeach</select><input type="hidden" name="idempotency_key" value="retention-submit-{{ $release->id }}"><button class="font-bold text-[var(--brand-primary)]">Submit</button></form>@elseif($release->status==='pending_approval')<form method="post" action="/admin/billing/retention-releases/{{ $release->id }}/activate">@csrf<button class="font-bold text-emerald-700">Validasi approval</button></form>@elseif($release->status==='approved')<form method="post" action="/admin/billing/retention-releases/{{ $release->id }}/post">@csrf<button class="font-bold text-violet-700">Post AR</button></form>@else {{ $release->journal?->number }} @endif</td></tr>@empty<tr><td colspan="6" class="p-8 text-center">Belum ada release retensi.</td></tr>@endforelse</tbody></table></div></div>
<button type="button" class="inline-flex inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="retention-release-drawer" aria-haspopup="dialog"><x-ui.icon name="plus" class="h-4 w-4" />Release Retensi</button>
<x-ui.drawer id="billing-create-drawer" title="Draft Progress Billing">
<form method="post" action="/admin/billing" class="grid gap-4">@csrf<h2 class="font-bold">Draft Progress Billing</h2><select name="project_id" required class="rounded-xl border p-3"><option value="">Proyek aktif</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->code }} · {{ $project->name }}</option>@endforeach</select><input name="number" required placeholder="Nomor billing" class="rounded-xl border p-3"><div class="grid grid-cols-2 gap-2"><input type="date" name="billing_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-3"><input type="date" name="due_date" class="rounded-xl border p-3"></div><input type="number" step=".0001" min=".0001" max="100" name="progress_percent" required placeholder="Progress %" class="rounded-xl border p-3"><div class="grid grid-cols-3 gap-2"><input type="number" step=".01" name="gross_amount" required placeholder="Gross (DPP)" class="rounded-xl border p-3"><input type="number" step=".0001" min="0" max="100" name="retention_percent" value="{{ \App\Models\CompanySetting::val(app(\App\Support\Tenancy\CurrentCompany::class)->id(), 'default_retention_percent') }}" required placeholder="Retensi %" class="rounded-xl border p-3"><input type="number" step=".01" min="0" name="advance_recovery" value="0" required placeholder="Advance" class="rounded-xl border p-3"></div><select name="tax_rate_id" class="rounded-xl border p-3"><option value="">Tanpa PPN</option>@foreach($taxRates as $rate)<option value="{{ $rate->id }}">PPN {{ $rate->name }} ({{ number_format($rate->rate_percent, 2, ',', '.') }}%)</option>@endforeach</select><input name="idempotency_key" value="billing-{{ Str::uuid() }}" required class="rounded-xl border p-3"><button class="rounded-xl bg-[var(--brand-primary)] p-3 text-white">Buat draft</button></form>
</x-ui.drawer>

<x-ui.drawer id="retention-release-drawer" title="Release Retensi">
<form method="post" action="/admin/billing/retention-releases" class="grid gap-4">@csrf<h2 class="font-bold">Release Retensi</h2><select name="project_id" required class="rounded-xl border p-3">@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->code }} — {{ $project->name }}</option>@endforeach</select><input name="number" required placeholder="Nomor release" class="rounded-xl border p-3"><input type="date" name="release_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-3"><input type="number" step=".01" min=".01" name="amount" required placeholder="Nilai release" class="rounded-xl border p-3"><input name="idempotency_key" value="retention-{{ Str::uuid() }}" required class="rounded-xl border p-3"><button class="rounded-xl bg-emerald-700 p-3 text-white">Buat draft release</button></form>
</x-ui.drawer>

<button type="button" class="btn-brand inline-flex min-h-[42px] items-center gap-2 rounded-xl px-4 text-sm font-bold shadow-sm" data-drawer-open="credit-note-drawer" aria-haspopup="dialog"><x-ui.icon name="minus" class="h-4 w-4" />Credit Note</button>
<button type="button" class="inline-flex min-h-[42px] items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 text-sm font-bold text-red-700 shadow-sm" data-drawer-open="write-off-drawer" aria-haspopup="dialog"><x-ui.icon name="trash" class="h-4 w-4" />Ajukan Write-off</button>

@if($writeOffs->where('status','pending_approval')->isNotEmpty())<div class="mt-8 rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 class="text-lg font-black text-amber-900">Write-off Menunggu Persetujuan</h2><p class="mt-1 text-sm text-amber-800">Pengaju tidak dapat menyetujui pengajuannya sendiri. Setelah disetujui, jurnal beban piutang diposting permanen.</p><div class="mt-3 space-y-3">@foreach($writeOffs->where('status','pending_approval') as $writeOff)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-200 bg-white p-3"><div><strong>{{ $writeOff->number }}</strong> · {{ $writeOff->billing?->number }}<p class="text-sm text-slate-500">Rp {{ number_format((float)$writeOff->amount,2,',','.') }} — {{ $writeOff->reason }} <span class="text-xs">diajukan {{ $writeOff->request_date->format('d/m/Y') }}</span></p></div><form method="post" action="/admin/billing/write-offs/{{ $writeOff->id }}/decide" class="flex flex-wrap gap-2">@csrf<input type="date" name="posting_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-2"><button name="decision" value="approve" class="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Setujui & Posting</button></form><form method="post" action="/admin/billing/write-offs/{{ $writeOff->id }}/decide" class="flex gap-2">@csrf<input name="notes" placeholder="Alasan penolakan" class="rounded-xl border p-2 w-44"><button name="decision" value="reject" class="rounded-xl border border-red-300 px-4 py-2 font-bold text-red-700">Tolak</button></form></div>@endforeach</div></div>@endif

<div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><h2 class="p-5 pb-0 text-lg font-black">Riwayat Credit Note & Write-off</h2><table class="w-full text-sm"><thead><tr class="border-t"><th class="p-3 text-left">Tipe</th><th class="p-3 text-left">Nomor</th><th class="p-3 text-left">Billing</th><th class="p-3 text-left">Tanggal</th><th class="p-3 text-right">Nilai</th><th class="p-3 text-left">Status / Jurnal</th></tr></thead><tbody>@forelse($creditNotes as $note)<tr class="border-t"><td class="p-3 font-bold text-violet-700">CREDIT NOTE</td><td class="p-3 font-mono">{{ $note->number }}</td><td class="p-3">{{ $note->billing?->number }}</td><td class="p-3">{{ $note->note_date->format('d/m/Y') }}</td><td class="p-3 text-right">{{ number_format((float)$note->amount,2,',','.') }}</td><td class="p-3 font-mono">{{ $note->journal?->number }}</td></tr>@endforeach @forelse($writeOffs as $writeOff)<tr class="border-t"><td class="p-3 font-bold text-red-700">WRITE-OFF</td><td class="p-3 font-mono">{{ $writeOff->number }}</td><td class="p-3">{{ $writeOff->billing?->number }}</td><td class="p-3">{{ $writeOff->request_date->format('d/m/Y') }}</td><td class="p-3 text-right">{{ number_format((float)$writeOff->amount,2,',','.') }}</td><td class="p-3 uppercase">{{ $writeOff->status }}</td></tr>@endforeach @if($creditNotes->isEmpty() && $writeOffs->isEmpty())<tr><td colspan="6" class="p-8 text-center">Belum ada penyesuaian piutang.</td></tr>@endif</tbody></table></div>

<x-ui.drawer id="credit-note-drawer" title="Credit Note Piutang">
<form method="post" action="#" data-billing-action="/admin/billing/BILLING_ID/credit-notes" class="grid gap-4 js-billing-form">@csrf<h2 class="font-bold">Credit Note</h2><p class="text-sm text-slate-500">Mengurangi tagihan posted: Debit revenue, Kredit AR. Tidak boleh melebihi sisa piutang billing.</p><select name="progress_billing_id" required class="rounded-xl border p-3"><option value="">Pilih billing posted</option>@foreach($billings->where('status','posted') as $b)<option value="{{ $b->id }}">{{ $b->number }} · Net AR {{ number_format((float)$b->net_receivable,0,',','.') }}</option>@endforeach</select><input type="number" step=".01" min=".01" name="amount" required placeholder="Nilai credit note" class="rounded-xl border p-3"><input type="date" name="note_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-3"><textarea name="reason" required rows="2" placeholder="Alasan (koreksi tagihan / diskon / dsb)" class="rounded-xl border p-3"></textarea><input name="idempotency_key" value="cn-{{ Str::uuid() }}" required class="rounded-xl border p-3"><button class="rounded-xl bg-[var(--brand-primary)] p-3 text-white">Posting Credit Note</button></form>
</x-ui.drawer>

<x-ui.drawer id="write-off-drawer" title="Pengajuan Write-off Piutang">
<form method="post" action="#" data-billing-action="/admin/billing/BILLING_ID/write-offs" class="grid gap-4 js-billing-form">@csrf<h2 class="font-bold">Write-off (Hapus Buku)</h2><p class="text-sm text-slate-500">Untuk piutang tak tertagih. Memerlukan persetujuan user lain sebelum jurnal beban piutang diposting.</p><select name="progress_billing_id" required class="rounded-xl border p-3"><option value="">Pilih billing posted</option>@foreach($billings->where('status','posted') as $b)<option value="{{ $b->id }}">{{ $b->number }} · Net AR {{ number_format((float)$b->net_receivable,0,',','.') }}</option>@endforeach</select><input type="number" step=".01" min=".01" name="amount" required placeholder="Nilai write-off" class="rounded-xl border p-3"><input type="date" name="request_date" value="{{ today()->toDateString() }}" required class="rounded-xl border p-3"><textarea name="reason" required rows="2" placeholder="Dasar hapus buku (gugur tagih, tutup buku, dsb)" class="rounded-xl border p-3"></textarea><input name="idempotency_key" value="wo-{{ Str::uuid() }}" required class="rounded-xl border p-3"><button class="rounded-xl bg-red-700 p-3 text-white">Ajukan Write-off</button></form>
</x-ui.drawer>
<script>document.querySelectorAll('form.js-billing-form').forEach(function(f){f.addEventListener('submit',function(e){var b=f.querySelector('[name=progress_billing_id]');if(b&&b.value){f.action=f.getAttribute('data-billing-action').replace('BILLING_ID',b.value);}});});</script>
</x-layouts.app>
