<x-layouts.app title="Routing dan Biaya Produksi">
<div class="page-container">
    <div class="flex flex-wrap gap-4"><a href="/admin/manufacturing" class="text-sm font-bold text-[var(--brand-primary)]">&larr; Manufacturing Control</a>@if(auth()->user()->hasPermission('report.view',app(\App\Support\Tenancy\CurrentCompany::class)->id()))<a href="/admin/reports/manufacturing" class="text-sm font-bold text-emerald-700">Lihat Rekonsiliasi WIP &rarr;</a>@endif</div>
    <h1 class="mt-3 text-2xl font-bold tracking-tight">Routing, Work Center, dan Biaya Konversi</h1>
    <p class="mt-2 max-w-4xl text-slate-500">Tetapkan urutan kerja dan waktu standar pada BOM. Ketika jam aktual dicatat, sistem menghitung tenaga kerja serta overhead dari tarif work center, mendebit Manufacturing WIP, dan menampilkan variance waktu/biaya.</p>
    @if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif

    @if(auth()->user()->hasPermission('manufacturing.manage', app(\App\Support\Tenancy\CurrentCompany::class)->id()))
    <div class="mt-8 grid gap-5 lg:grid-cols-2">
        <form method="post" action="/admin/manufacturing/work-centers" class="grid gap-3 rounded-2xl border bg-white p-5">@csrf
            <h2 class="font-bold">Buat Work Center dan Tarif</h2><p class="text-sm text-slate-500">Work center adalah lokasi/kelompok sumber daya seperti Cutting, Bending, Welding, atau Assembly.</p>
            <div class="grid gap-3 sm:grid-cols-2"><input name="code" required placeholder="Kode, contoh WC-WELD" class="rounded-xl border p-3"><input name="name" required placeholder="Nama work center" class="rounded-xl border p-3"></div>
            <div class="grid gap-3 sm:grid-cols-2"><input type="number" step=".01" min="0" name="labor_rate_per_hour" value="0" required placeholder="Tarif tenaga kerja/jam" class="rounded-xl border p-3"><input type="number" step=".01" min="0" name="overhead_rate_per_hour" value="0" required placeholder="Tarif overhead/jam" class="rounded-xl border p-3"></div>
            <button class="rounded-xl bg-[var(--brand-primary)] p-3 font-bold text-white">Simpan Work Center</button>
        </form>
        <div class="rounded-2xl border bg-white p-5"><h2 class="font-bold">Pemetaan Jurnal Biaya Konversi</h2><p class="mt-1 text-sm text-slate-500">Ketiga akun wajib disiapkan Finance sebelum pencatatan jam aktual.</p>
            @if(auth()->user()->hasPermission('finance.manage', app(\App\Support\Tenancy\CurrentCompany::class)->id()))
            <div class="mt-3 grid gap-2">@foreach(['wip_debit'=>'Debit — Manufacturing WIP','labor_absorption_credit'=>'Kredit — Penyerapan Tenaga Kerja','overhead_absorption_credit'=>'Kredit — Penyerapan Overhead'] as $side=>$label)
                <form method="post" action="/admin/finance/mappings" class="grid gap-2 sm:grid-cols-[1fr_1fr_auto]">@csrf<input type="hidden" name="event_type" value="production_conversion_cost"><input type="hidden" name="entry_side" value="{{ $side }}"><label class="self-center text-sm font-semibold">{{ $label }}</label><select name="account_id" required class="rounded-xl border p-2"><option value="">Pilih akun</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(optional($mappings->firstWhere('entry_side',$side))->account_id===$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 text-white">Simpan</button></form>
            @endforeach</div>
            @else<p class="mt-3 rounded-xl bg-slate-50 p-3 text-sm">Konfigurasi akun hanya dapat dilakukan oleh Finance.</p>@endif
        </div>
    </div>
    @endif

    <section class="mt-10"><h2 class="text-xl font-black">1. Routing Standar per BOM</h2><p class="mt-1 text-sm text-slate-500">Sequence menentukan urutan kerja; menit standar per unit menjadi dasar variance terhadap jam aktual.</p>
        <div class="mt-4 grid gap-4 lg:grid-cols-2">@forelse($boms as $bom)<x-ui.card><h3 class="font-bold">{{ $bom->code }} — {{ $bom->outputItem?->name }}</h3><div class="mt-3 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Urutan</th><th>Operasi</th><th>Work Center</th><th>Menit/unit</th></tr></thead><tbody>@forelse($bom->routingOperations as $operation)<tr><td>{{ $operation->sequence }}</td><td>{{ $operation->name }}</td><td>{{ $operation->workCenter?->code }}</td><td>{{ $operation->standard_minutes_per_unit }}</td></tr>@empty<tr><td colspan="4" class="text-amber-700">Belum ada routing. Tambahkan tahap kerja agar biaya dan variance dapat dihitung.</td></tr>@endforelse</tbody></table></div>
            @if(auth()->user()->hasPermission('manufacturing.manage', app(\App\Support\Tenancy\CurrentCompany::class)->id()))<form method="post" action="/admin/manufacturing/boms/{{ $bom->id }}/routing-operations" class="mt-4 grid gap-2 sm:grid-cols-2">@csrf<select name="work_center_id" required class="rounded-xl border p-2"><option value="">Pilih work center</option>@foreach($workCenters as $wc)<option value="{{ $wc->id }}">{{ $wc->code }} — {{ $wc->name }}</option>@endforeach</select><input type="number" min="1" name="sequence" required placeholder="Urutan" class="rounded-xl border p-2"><input name="name" required placeholder="Nama operasi" class="rounded-xl border p-2"><input type="number" step=".0001" min=".0001" name="standard_minutes_per_unit" required placeholder="Menit standar/unit" class="rounded-xl border p-2"><textarea name="work_instruction" placeholder="Instruksi kerja dan kriteria proses" class="rounded-xl border p-2 sm:col-span-2"></textarea><button class="rounded-xl bg-slate-800 p-2 text-white sm:col-span-2">Tambah atau Perbarui Tahap Routing</button></form>@endif
        </x-ui.card>@empty<div class="rounded-2xl border border-dashed p-8">Belum ada BOM.</div>@endforelse</div>
    </section>

    <section class="mt-10"><h2 class="text-xl font-black">2. Realisasi Operasi dan Variance</h2><p class="mt-1 text-sm text-slate-500">Variance positif berarti jam/biaya aktual melebihi standar dan perlu dianalisis.</p><div class="mt-4 space-y-4">@forelse($orders as $order)
        @php($actualConversion = bcadd((string)$order->actual_labor_cost,(string)$order->actual_overhead_cost,2))
        <x-ui.card><div class="flex flex-wrap justify-between gap-3"><div><h3 class="font-bold">{{ $order->number }} — {{ $order->bom?->outputItem?->name }}</h3><p class="text-sm text-slate-500">Material Rp {{ number_format((float)$order->actual_material_cost,2,',','.') }} · Tenaga kerja Rp {{ number_format((float)$order->actual_labor_cost,2,',','.') }} · Overhead Rp {{ number_format((float)$order->actual_overhead_cost,2,',','.') }}</p></div><span class="rounded-lg bg-slate-100 px-3 py-1 text-xs font-bold">{{ strtoupper($order->status) }}</span></div>
        <div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Operasi</th><th>Qty</th><th>Jam Standar</th><th>Jam Aktual</th><th>Variance Jam</th><th>Biaya Aktual</th></tr></thead><tbody>@forelse($order->operationLogs as $log)@php($standardHours=bcdiv(bcmul((string)$log->quantity_processed,(string)$log->routingOperation->standard_minutes_per_unit,4),'60',4))<tr><td>{{ $log->routingOperation->sequence }}. {{ $log->routingOperation->name }}</td><td>{{ $log->quantity_processed }}</td><td>{{ $standardHours }}</td><td>{{ $log->actual_hours }}</td><td class="font-bold {{ bccomp((string)$log->actual_hours,$standardHours,4)===1?'text-red-700':'text-emerald-700' }}">{{ bcsub((string)$log->actual_hours,$standardHours,4) }}</td><td>Rp {{ number_format((float)bcadd((string)$log->labor_cost,(string)$log->overhead_cost,2),2,',','.') }}</td></tr>@empty<tr><td colspan="6" class="text-slate-500">Belum ada realisasi operasi.</td></tr>@endforelse</tbody></table></div>
        @if(in_array($order->status,['released','in_progress']) && auth()->user()->hasPermission('manufacturing.manage', app(\App\Support\Tenancy\CurrentCompany::class)->id()))<div class="mt-4 grid gap-3 lg:grid-cols-2">@foreach($order->bom?->routingOperations??[] as $operation)<form method="post" action="/admin/manufacturing/orders/{{ $order->id }}/operations/{{ $operation->id }}" class="grid gap-2 rounded-xl bg-sky-50 p-4">@csrf<h4 class="font-bold">{{ $operation->sequence }}. {{ $operation->name }} / {{ $operation->workCenter?->code }}</h4><input type="number" step=".0001" min=".0001" name="quantity_processed" required placeholder="Kuantitas diproses" class="rounded-xl border p-2"><input type="number" step=".0001" min=".0001" name="actual_hours" required placeholder="Jam aktual" class="rounded-xl border p-2"><textarea name="notes" placeholder="Catatan realisasi atau penyebab variance" class="rounded-xl border p-2"></textarea><input type="hidden" name="idempotency_key" value="operation-{{ Str::uuid() }}"><button class="rounded-xl bg-[var(--brand-primary)] p-2 font-bold text-white">Post Jam Aktual dan Biaya ke WIP</button></form>@endforeach</div>@endif
        </x-ui.card>
    @empty<div class="rounded-2xl border border-dashed p-8">Belum ada production order.</div>@endforelse</div></section>
</div>
</x-layouts.app>>
