const { chromium } = require('playwright');
const path = require('path');
const BASE = 'http://127.0.0.1:8899';
const OUT = path.join(__dirname, '..', 'public', 'marketing', 'screens');
(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await ctx.newPage();
  await page.goto(BASE + '/login', { waitUntil: 'networkidle' });
  await page.type('input[type=email]', 'admin@grahapondasi.test', { delay: 12 });
  await page.type('input[type=password]', 'password', { delay: 12 });
  await page.locator('button[type=submit]').first().click();
  await page.waitForTimeout(1300);
  await page.goto(BASE + '/admin/experience', { waitUntil: 'networkidle' });
  await page.waitForTimeout(500);
  const dash = page.locator('fieldset', { has: page.locator('legend', { hasText: 'Dashboard Builder' }) });
  await dash.scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  // Uji move down pada item pertama
  const first = dash.locator('[data-dash-item]').first();
  const before = await first.textContent();
  await dash.locator('[data-dash-move="1"]').first().click();
  const after = await dash.locator('[data-dash-item]').nth(1).textContent();
  console.log('MOVE OK: ' + (before && after && before.trim() !== after.trim() ? 'REORDERED' : 'CHECK'));
  await dash.screenshot({ path: path.join(OUT, 'dashboard-builder-v3-1440.png') });
  console.log('OK dashboard-builder-v3-1440');
  // Drawer a11y: buka documents drawer, cek aria-expanded + fokus
  await page.goto(BASE + '/admin/documents', { waitUntil: 'networkidle' });
  await page.waitForTimeout(400);
  const opener = page.locator('[data-drawer-open="document-create-drawer"]');
  await opener.click();
  await page.waitForTimeout(400);
  const expanded = await opener.getAttribute('aria-expanded');
  console.log('ARIA-EXPANDED: ' + expanded);
  await page.keyboard.press('Escape');
  await page.waitForTimeout(300);
  const focusOk = await page.evaluate(() => document.activeElement?.hasAttribute('data-drawer-open'));
  console.log('FOCUS-RESTORED: ' + (focusOk ? 'YES' : 'NO'));
  await browser.close();
})();
