<x-layouts.app title="Storage & File"><div class="page-container" x-data="{tab:'overview', driver:'local', preset:'custom'}">
<x-ui.page-header title="Storage & File" subtitle="Konfigurasi Local atau S3-compatible per perusahaan. Credential terenkripsi dan tidak pernah ditampilkan kembali." />
@if(session('status'))<div class="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
@if($errors->any())<div class="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<nav class="mt-6 flex gap-2 overflow-x-auto rounded-xl border bg-white p-2 dark:bg-slate-900" aria-label="Storage tabs">
@foreach(['overview'=>'Overview','profiles'=>'Storage Profiles','retention'=>'Retention','usage'=>'Usage'] as $key=>$label)<button type="button" @click="tab='{{ $key }}'" :class="tab==='{{ $key }}'?'bg-sky-700 text-white':'text-slate-600'" class="min-h-10 whitespace-nowrap rounded-lg px-4 text-sm font-bold">{{ $label }}</button>@endforeach
</nav>
<section x-show="tab==='overview'" class="mt-6 grid gap-4 lg:grid-cols-2">
@foreach(['Evidence'=>$evidenceProfile,'Documents'=>$documentProfile] as $label=>$active)<x-ui.card><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Active {{ $label }} Storage</p><h2 class="mt-2 text-xl font-black">{{ $active?->name ?? 'Environment fallback' }}</h2><div class="mt-3 flex flex-wrap gap-2"><x-ui.badge status="{{ $active?->status ?? 'active' }}" label="{{ $active ? strtoupper($active->driver === 's3' ? 'S3 Compatible' : 'Local') : strtoupper(config('objectstorage.'.(strtolower($label)==='documents'?'document_disk':'evidence_disk'))) }}" />@if($active)<x-ui.badge status="active" label="{{ str($active->provider_preset)->replace('-',' ')->title() }}" /><x-ui.badge status="{{ strtolower($active->last_test_status ?? 'draft') }}" label="{{ $active->last_test_status ?? 'NOT TESTED' }}" />@endif</div>@if($active)<dl class="mt-4 grid grid-cols-2 gap-2 text-sm"><dt class="text-slate-500">Bucket</dt><dd>{{ $active->bucket ?? 'Private local root' }}</dd><dt class="text-slate-500">Endpoint</dt><dd>{{ $active->endpointHostname() ?? 'Local' }}</dd><dt class="text-slate-500">Region</dt><dd>{{ $active->region ?? '-' }}</dd><dt class="text-slate-500">Last tested</dt><dd>{{ $active->last_tested_at?->format('d M Y H:i') ?? '-' }}</dd></dl>@endif</x-ui.card>@endforeach
</section>
<section x-show="tab==='profiles'" x-cloak class="mt-6 space-y-5">
<x-ui.card><h2 class="text-lg font-black">Tambah Storage Profile</h2><form method="post" action="{{ route('storage-profiles.store') }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf
<label class="text-sm font-semibold">Storage Provider<select name="driver" x-model="driver" class="mt-1 w-full rounded-xl border p-3"><option value="local">Local Server</option><option value="s3">S3-Compatible</option></select></label>
<label class="text-sm font-semibold">Profile Name<input name="name" required class="mt-1 w-full rounded-xl border p-3" placeholder="R2 Primary"></label>
<label x-show="driver==='s3'" class="text-sm font-semibold">Preset<select name="provider_preset" x-model="preset" class="mt-1 w-full rounded-xl border p-3"><option value="cloudflare-r2">Cloudflare R2</option><option value="aws-s3">AWS S3</option><option value="wasabi">Wasabi</option><option value="minio">MinIO</option><option value="backblaze-b2">Backblaze B2</option><option value="digitalocean-spaces">DigitalOcean Spaces</option><option value="custom">Custom</option></select></label>
<input x-show="driver==='local'" type="hidden" name="provider_preset" value="custom">
<label x-show="driver==='s3'" class="text-sm font-semibold">Endpoint<input name="endpoint" class="mt-1 w-full rounded-xl border p-3" placeholder="https://ACCOUNT_ID.r2.cloudflarestorage.com"></label>
<label x-show="driver==='s3'" class="text-sm font-semibold">Region<input name="region" :value="preset==='cloudflare-r2'?'auto':''" class="mt-1 w-full rounded-xl border p-3"></label>
<label x-show="driver==='s3'" class="text-sm font-semibold">Bucket<input name="bucket" class="mt-1 w-full rounded-xl border p-3"></label>
<label x-show="driver==='s3'" class="text-sm font-semibold">Access Key<input type="password" name="access_key_encrypted" autocomplete="new-password" class="mt-1 w-full rounded-xl border p-3"></label>
<label x-show="driver==='s3'" class="text-sm font-semibold">Secret Key<input type="password" name="secret_key_encrypted" autocomplete="new-password" class="mt-1 w-full rounded-xl border p-3"></label>
<label x-show="driver==='s3'" class="text-sm font-semibold">Base URL (opsional)<input name="base_url" class="mt-1 w-full rounded-xl border p-3"></label>
<label class="text-sm font-semibold">Temporary URL TTL (menit)<input type="number" min="1" max="1440" name="temporary_url_minutes" value="15" class="mt-1 w-full rounded-xl border p-3"></label>
<label x-show="driver==='s3'" class="flex items-center gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" name="use_path_style_endpoint" value="1" :checked="preset==='cloudflare-r2'||preset==='minio'"> Path Style Endpoint</label>
<div class="md:col-span-2"><x-ui.button type="submit">Simpan Draft</x-ui.button></div></form></x-ui.card>
@foreach($profiles as $profile)<x-ui.card x-data="{editing:false}"><div class="flex flex-wrap items-start justify-between gap-4"><div><h3 class="text-lg font-black">{{ $profile->name }}</h3><p class="text-sm text-slate-500">{{ strtoupper($profile->driver) }} · {{ str($profile->provider_preset)->replace('-',' ')->title() }} · {{ $profile->endpointHostname() ?? 'private local root' }}</p><p class="mt-2 font-mono text-xs">Access Key: {{ $profile->maskedAccessKey() }} · Secret: ••••••••••••••</p></div><x-ui.badge status="{{ $profile->status }}" /></div><div class="mt-4 flex flex-wrap gap-2"><x-ui.button type="button" variant="secondary" @click="editing=!editing">Edit / Rotasi Credential</x-ui.button><form method="post" action="{{ route('storage-profiles.test',$profile) }}">@csrf<x-ui.button type="submit" variant="secondary">Test Connection</x-ui.button></form><form method="post" action="{{ route('storage-profiles.activate',$profile) }}">@csrf<label class="mr-2 text-xs"><input type="checkbox" name="evidence" value="1" checked> Evidence</label><label class="mr-2 text-xs"><input type="checkbox" name="document" value="1" checked> Documents</label><x-ui.button type="submit">Set Active</x-ui.button></form><form method="post" action="{{ route('storage-profiles.disable',$profile) }}">@csrf<x-ui.button type="submit" variant="danger">Disable</x-ui.button></form></div>
<form x-show="editing" x-cloak method="post" action="{{ route('storage-profiles.update',$profile) }}" class="mt-5 grid gap-3 border-t pt-5 md:grid-cols-2">@csrf @method('PUT')
<input type="hidden" name="driver" value="{{ $profile->driver }}"><input type="hidden" name="provider_preset" value="{{ $profile->provider_preset }}"><input type="hidden" name="use_path_style_endpoint" value="{{ $profile->use_path_style_endpoint ? 1 : 0 }}">
<label class="text-sm font-semibold">Profile Name<input name="name" value="{{ $profile->name }}" required class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Temporary URL TTL<input type="number" name="temporary_url_minutes" min="1" max="1440" value="{{ $profile->temporary_url_minutes }}" class="mt-1 w-full rounded-xl border p-3"></label>
@if($profile->driver==='s3')<label class="text-sm font-semibold">Endpoint<input name="endpoint" value="{{ $profile->endpoint }}" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Region<input name="region" value="{{ $profile->region }}" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Bucket<input name="bucket" value="{{ $profile->bucket }}" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Base URL<input name="base_url" value="{{ $profile->base_url }}" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Ganti Access Key <span class="block text-xs font-normal text-slate-500">Kosong = pertahankan credential lama</span><input type="password" name="access_key_encrypted" autocomplete="new-password" class="mt-1 w-full rounded-xl border p-3" placeholder="••••••••••{{ mb_substr((string)$profile->access_key_encrypted,-4) }}"></label><label class="text-sm font-semibold">Ganti Secret Key <span class="block text-xs font-normal text-slate-500">Kosong = pertahankan credential lama</span><input type="password" name="secret_key_encrypted" autocomplete="new-password" class="mt-1 w-full rounded-xl border p-3" placeholder="••••••••••••••"></label>@endif
<div class="md:col-span-2"><x-ui.button type="submit">Simpan Perubahan</x-ui.button></div></form></x-ui.card>@endforeach
</section>
<section x-show="tab==='retention'" x-cloak class="mt-6"><x-ui.card><h2 class="font-black">Retention Lifecycle</h2><p class="mt-2 text-sm text-slate-500">Kebijakan retensi tetap dikelola oleh service existing. As-built, dossier, dan handover dilindungi dari penghapusan fisik otomatis.</p><a href="{{ route('settings.index') }}" class="mt-4 inline-block font-bold text-sky-700">Buka kebijakan perusahaan →</a></x-ui.card></section>
<section x-show="tab==='usage'" x-cloak class="mt-6 grid gap-4 sm:grid-cols-2"><x-ui.card><p class="text-xs uppercase text-slate-500">Objects</p><p class="mt-2 text-3xl font-black">{{ number_format($objects) }}</p></x-ui.card><x-ui.card><p class="text-xs uppercase text-slate-500">Usage</p><p class="mt-2 text-3xl font-black">{{ number_format($bytes/1073741824,2) }} GB</p><a href="{{ route('storage.dashboard') }}" class="text-sm font-bold text-sky-700">Storage dashboard →</a></x-ui.card></section>
</div></x-layouts.app>
